CREATE TABLE IF NOT EXISTS processes (
	process_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	process_name text NOT NULL UNIQUE,
	url text NULL,
	action text NULL,
	run_data text NULL,
	is_running boolean NOT NULL DEFAULT false,
	run_started timestamp NULL,
	run_ended timestamp NULL,
	run_every numeric(18,4) NULL,
	is_enabled boolean NOT NULL DEFAULT true,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	maximum_run_time integer NULL,
	is_timed_out boolean NOT NULL DEFAULT false,
	run_every_type text NULL,
	data text NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_processes_process_name ON processes(process_name);

CREATE OR REPLACE FUNCTION get_process_rows()
RETURNS TABLE ("ProcessID" integer,"ProcessName" text,"Url" text,"Action" text,"RunData" text,"IsRunning" boolean,"RunStarted" timestamp,"RunEnded" timestamp,"RunEvery" numeric,"IsEnabled" boolean,"DateCreated" timestamp,"LastUpdated" timestamp,"MaximumRunTime" integer,"IsTimedOut" boolean,"RunEveryType" text,"Data" text)
LANGUAGE sql AS $$
	SELECT process_id,process_name,url,action,run_data,is_running,run_started,run_ended,run_every,is_enabled,date_created,last_updated,maximum_run_time,is_timed_out,run_every_type,data
	FROM processes;
$$;

CREATE OR REPLACE FUNCTION insert_process_sp(p_process_name text,p_url text,p_action text,p_run_data text,p_is_running boolean,p_run_started timestamp with time zone,p_run_ended timestamp with time zone,p_run_every numeric,p_is_enabled boolean,p_maximum_run_time integer,p_is_timed_out boolean)
RETURNS TABLE ("ProcessID" integer)
LANGUAGE sql AS $$
	INSERT INTO processes(process_name,url,action,run_data,is_running,run_started,run_ended,run_every,is_enabled,date_created,last_updated,maximum_run_time,is_timed_out)
	VALUES(p_process_name,p_url,p_action,p_run_data,p_is_running,p_run_started,p_run_ended,p_run_every,p_is_enabled,now(),now(),p_maximum_run_time,p_is_timed_out)
	RETURNING process_id;
$$;

CREATE OR REPLACE FUNCTION update_process_sp(p_process_id integer,p_process_name text,p_url text,p_action text,p_run_data text,p_is_running boolean,p_run_started timestamp with time zone,p_run_ended timestamp with time zone,p_run_every numeric,p_is_enabled boolean,p_maximum_run_time integer,p_is_timed_out boolean,p_run_every_type text DEFAULT NULL,p_data text DEFAULT NULL)
RETURNS void
LANGUAGE sql AS $$
	UPDATE processes
	SET process_name=p_process_name,
		url=p_url,
		action=p_action,
		run_data=p_run_data,
		is_running=p_is_running,
		run_started=p_run_started,
		run_ended=p_run_ended,
		run_every=p_run_every,
		is_enabled=p_is_enabled,
		last_updated=now(),
		maximum_run_time=p_maximum_run_time,
		is_timed_out=p_is_timed_out,
		run_every_type=p_run_every_type,
		data=p_data
	WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION remove_process_sp(p_process_id integer)
RETURNS void
LANGUAGE sql AS $$
	DELETE FROM processes WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION get_process_sp(p_process_id integer)
RETURNS TABLE ("ProcessID" integer,"ProcessName" text,"Url" text,"Action" text,"RunData" text,"IsRunning" boolean,"RunStarted" timestamp,"RunEnded" timestamp,"RunEvery" numeric,"IsEnabled" boolean,"DateCreated" timestamp,"LastUpdated" timestamp,"MaximumRunTime" integer,"IsTimedOut" boolean,"RunEveryType" text,"Data" text)
LANGUAGE sql AS $$
	SELECT * FROM get_process_rows() WHERE "ProcessID"=p_process_id;
$$;

CREATE OR REPLACE FUNCTION get_processes_sp()
RETURNS TABLE ("ProcessID" integer,"ProcessName" text,"Url" text,"Action" text,"RunData" text,"IsRunning" boolean,"RunStarted" timestamp,"RunEnded" timestamp,"RunEvery" numeric,"IsEnabled" boolean,"DateCreated" timestamp,"LastUpdated" timestamp,"MaximumRunTime" integer,"IsTimedOut" boolean,"RunEveryType" text,"Data" text)
LANGUAGE sql AS $$
	SELECT * FROM get_process_rows();
$$;

CREATE OR REPLACE FUNCTION copy_process_sp(p_process_id integer)
RETURNS TABLE ("ProcessID" integer)
LANGUAGE sql AS $$
	INSERT INTO processes(process_name,url,action,run_data,is_running,run_started,run_ended,run_every,is_enabled,date_created,last_updated,maximum_run_time,is_timed_out,run_every_type,data)
	SELECT process_name || ' - Copy',url,action,run_data,is_running,run_started,run_ended,run_every,is_enabled,now(),now(),maximum_run_time,is_timed_out,run_every_type,data
	FROM processes
	WHERE process_id=p_process_id
	RETURNING process_id;
$$;

CREATE OR REPLACE FUNCTION update_process_run_data_sp(p_process_id integer,p_run_data text)
RETURNS void
LANGUAGE sql AS $$
	UPDATE processes SET run_data=p_run_data,last_updated=now() WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION mark_process_as_running_sp(p_process_id integer)
RETURNS void
LANGUAGE sql AS $$
	UPDATE processes SET is_running=true,last_updated=now() WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION mark_process_as_not_running_sp(p_process_id integer)
RETURNS void
LANGUAGE sql AS $$
	UPDATE processes SET is_running=false,last_updated=now() WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION mark_process_as_enabled_sp(p_process_id integer)
RETURNS void
LANGUAGE sql AS $$
	UPDATE processes SET is_enabled=true,last_updated=now() WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION mark_process_as_not_enabled_sp(p_process_id integer)
RETURNS void
LANGUAGE sql AS $$
	UPDATE processes SET is_enabled=false,last_updated=now() WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION mark_process_as_timed_out_sp(p_process_id integer)
RETURNS void
LANGUAGE sql AS $$
	UPDATE processes SET is_timed_out=true,last_updated=now() WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION mark_process_as_not_timed_out_sp(p_process_id integer)
RETURNS void
LANGUAGE sql AS $$
	UPDATE processes SET is_timed_out=false,last_updated=now() WHERE process_id=p_process_id;
$$;

CREATE OR REPLACE FUNCTION get_processes_sp_count_sp(p_search text)
RETURNS TABLE ("Total" integer)
LANGUAGE sql AS $$
	SELECT COUNT(*)::integer
	FROM processes
	WHERE process_id::text LIKE '%'||COALESCE(p_search,'')||'%'
		OR process_name LIKE '%'||COALESCE(p_search,'')||'%'
		OR url LIKE '%'||COALESCE(p_search,'')||'%'
		OR action LIKE '%'||COALESCE(p_search,'')||'%';
$$;

CREATE OR REPLACE FUNCTION get_processes_sp_paging_sp(p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer)
RETURNS TABLE ("ProcessID" integer,"ProcessName" text,"Url" text,"Action" text,"RunData" text,"IsRunning" boolean,"RunStarted" timestamp,"RunEnded" timestamp,"RunEvery" numeric,"IsEnabled" boolean,"DateCreated" timestamp,"LastUpdated" timestamp,"MaximumRunTime" integer,"IsTimedOut" boolean,"RunEveryType" text,"Data" text)
LANGUAGE sql AS $$
	SELECT *
	FROM get_process_rows()
	WHERE "ProcessID"::text LIKE '%'||COALESCE(p_search,'')||'%'
		OR "ProcessName" LIKE '%'||COALESCE(p_search,'')||'%'
		OR "Url" LIKE '%'||COALESCE(p_search,'')||'%'
		OR "Action" LIKE '%'||COALESCE(p_search,'')||'%'
	ORDER BY
		CASE WHEN p_sort_column='ProcessID' AND p_sort_ascending THEN "ProcessID" END ASC,
		CASE WHEN p_sort_column='ProcessID' AND NOT p_sort_ascending THEN "ProcessID" END DESC,
		CASE WHEN p_sort_column='ProcessName' AND p_sort_ascending THEN "ProcessName" END ASC,
		CASE WHEN p_sort_column='ProcessName' AND NOT p_sort_ascending THEN "ProcessName" END DESC,
		CASE WHEN p_sort_column='Url' AND p_sort_ascending THEN "Url" END ASC,
		CASE WHEN p_sort_column='Url' AND NOT p_sort_ascending THEN "Url" END DESC,
		CASE WHEN p_sort_column='Action' AND p_sort_ascending THEN "Action" END ASC,
		CASE WHEN p_sort_column='Action' AND NOT p_sort_ascending THEN "Action" END DESC,
		CASE WHEN p_sort_column='RunData' AND p_sort_ascending THEN "RunData" END ASC,
		CASE WHEN p_sort_column='RunData' AND NOT p_sort_ascending THEN "RunData" END DESC,
		CASE WHEN p_sort_column='RunStarted' AND p_sort_ascending THEN "RunStarted" END ASC,
		CASE WHEN p_sort_column='RunStarted' AND NOT p_sort_ascending THEN "RunStarted" END DESC,
		CASE WHEN p_sort_column='RunEnded' AND p_sort_ascending THEN "RunEnded" END ASC,
		CASE WHEN p_sort_column='RunEnded' AND NOT p_sort_ascending THEN "RunEnded" END DESC,
		CASE WHEN p_sort_column='DateCreated' AND p_sort_ascending THEN "DateCreated" END ASC,
		CASE WHEN p_sort_column='DateCreated' AND NOT p_sort_ascending THEN "DateCreated" END DESC,
		CASE WHEN p_sort_column='LastUpdated' AND p_sort_ascending THEN "LastUpdated" END ASC,
		CASE WHEN p_sort_column='LastUpdated' AND NOT p_sort_ascending THEN "LastUpdated" END DESC,
		"ProcessID" ASC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;

SELECT record_schema_migration('007_processes_repository_routines');

DROP FUNCTION IF EXISTS stored_procedure_has_parameter_sp(text,text);
DROP FUNCTION IF EXISTS "StoredProcedureHasParameterSp"(text,text);

CREATE OR REPLACE FUNCTION stored_procedure_has_parameter_sp(p_stored_procedure_name text,p_parameter_name text)
RETURNS TABLE (HasParameter integer) LANGUAGE sql AS $$
	SELECT CASE WHEN EXISTS (
		SELECT 1
		FROM information_schema.parameters
		WHERE specific_schema = current_schema()
			AND specific_name LIKE lower(p_stored_procedure_name) || '_%'
			AND parameter_name = lower(regexp_replace(trim(leading '@' FROM p_parameter_name), '([A-Z])', '_\1', 'g'))
	) THEN 1 ELSE 0 END::integer;
$$;

CREATE OR REPLACE FUNCTION "StoredProcedureHasParameterSp"(p_stored_procedure_name text,p_parameter_name text)
RETURNS TABLE (HasParameter integer) LANGUAGE sql AS $$
SELECT * FROM stored_procedure_has_parameter_sp(p_stored_procedure_name,p_parameter_name);
$$;
