DROP FUNCTION IF EXISTS get_session_subscription_rows();
DROP FUNCTION IF EXISTS insert_session_subscription_sp(text,integer,text,text,text,text,boolean,timestamp,text);
DROP FUNCTION IF EXISTS update_session_subscription_sp(integer,text,integer,text,text,text,text,boolean,timestamp,text);
DROP FUNCTION IF EXISTS remove_session_subscription_sp(integer);
DROP FUNCTION IF EXISTS get_session_subscription_sp(integer);
DROP FUNCTION IF EXISTS get_session_subscriptions_sp();
DROP FUNCTION IF EXISTS copy_session_subscription_sp(integer);
DROP FUNCTION IF EXISTS get_session_subscription_by_subscription_identity_sp(text);
DROP FUNCTION IF EXISTS mark_session_subscription_as_enabled_sp(integer);
DROP FUNCTION IF EXISTS mark_session_subscription_as_not_enabled_sp(integer);
DROP FUNCTION IF EXISTS update_session_subscription_data_sp(integer,text);
DROP FUNCTION IF EXISTS get_session_subscriptions_by_session_id_sp(integer);
DROP FUNCTION IF EXISTS get_session_subscriptions_by_subscriber_session_key_sp(text);
DROP FUNCTION IF EXISTS session_subscription_search_match(session_subscriptions,text);
DROP FUNCTION IF EXISTS get_session_subscriptions_sp_count_sp(text);
DROP FUNCTION IF EXISTS get_session_subscriptions_sp_paging_sp(text,text,boolean,integer,integer);
DROP FUNCTION IF EXISTS get_session_subscriptions_by_session_idsp_count_sp(integer,text);
DROP FUNCTION IF EXISTS get_session_subscriptions_by_session_idsp_paging_sp(integer,text,text,boolean,integer,integer);
CREATE TABLE IF NOT EXISTS session_subscriptions (
	session_subscription_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	subscription_identity text NOT NULL UNIQUE,
	session_id integer NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
	subscriber_session_key text NOT NULL,
	event_type text NOT NULL,
	delivery_mode text NOT NULL,
	callback_url text NULL,
	is_enabled boolean NOT NULL DEFAULT true,
	expiration_utc timestamp NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	data text NULL
);
CREATE INDEX IF NOT EXISTS ix_session_subscriptions_session_id ON session_subscriptions(session_id);
CREATE INDEX IF NOT EXISTS ix_session_subscriptions_subscriber_session_key ON session_subscriptions(subscriber_session_key);
CREATE INDEX IF NOT EXISTS ix_session_subscriptions_event_type ON session_subscriptions(event_type);

CREATE OR REPLACE FUNCTION get_session_subscription_rows()
RETURNS TABLE ("SessionSubscriptionID" integer,"SubscriptionIdentity" text,"SessionID" integer,"SubscriberSessionKey" text,"EventType" text,"DeliveryMode" text,"CallbackUrl" text,"IsEnabled" boolean,"ExpirationUtc" timestamp,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text)
LANGUAGE sql AS $$
	SELECT session_subscription_id,subscription_identity,session_id,subscriber_session_key,event_type,delivery_mode,callback_url,is_enabled,expiration_utc,date_created,last_updated,data
	FROM session_subscriptions;
$$;

CREATE OR REPLACE FUNCTION insert_session_subscription_sp(p_subscription_identity text,p_session_id integer,p_subscriber_session_key text,p_event_type text,p_delivery_mode text,p_callback_url text,p_is_enabled boolean,p_expiration_utc timestamp,p_data text)
RETURNS TABLE ("SessionSubscriptionID" integer) LANGUAGE sql AS $$
	INSERT INTO session_subscriptions(subscription_identity,session_id,subscriber_session_key,event_type,delivery_mode,callback_url,is_enabled,expiration_utc,date_created,last_updated,data)
	VALUES(p_subscription_identity,p_session_id,p_subscriber_session_key,p_event_type,p_delivery_mode,p_callback_url,p_is_enabled,p_expiration_utc,now(),now(),p_data)
	RETURNING session_subscription_id;
$$;

CREATE OR REPLACE FUNCTION update_session_subscription_sp(p_session_subscription_id integer,p_subscription_identity text,p_session_id integer,p_subscriber_session_key text,p_event_type text,p_delivery_mode text,p_callback_url text,p_is_enabled boolean,p_expiration_utc timestamp,p_data text)
RETURNS void LANGUAGE sql AS $$
	UPDATE session_subscriptions SET subscription_identity=p_subscription_identity,session_id=p_session_id,subscriber_session_key=p_subscriber_session_key,event_type=p_event_type,delivery_mode=p_delivery_mode,callback_url=p_callback_url,is_enabled=p_is_enabled,expiration_utc=p_expiration_utc,last_updated=now(),data=p_data
	WHERE session_subscription_id=p_session_subscription_id;
$$;

CREATE OR REPLACE FUNCTION remove_session_subscription_sp(p_session_subscription_id integer) RETURNS void LANGUAGE sql AS $$ DELETE FROM session_subscriptions WHERE session_subscription_id=p_session_subscription_id; $$;
CREATE OR REPLACE FUNCTION get_session_subscription_sp(p_session_subscription_id integer) RETURNS TABLE ("SessionSubscriptionID" integer,"SubscriptionIdentity" text,"SessionID" integer,"SubscriberSessionKey" text,"EventType" text,"DeliveryMode" text,"CallbackUrl" text,"IsEnabled" boolean,"ExpirationUtc" timestamp,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_subscription_rows() WHERE "SessionSubscriptionID"=p_session_subscription_id; $$;
CREATE OR REPLACE FUNCTION get_session_subscriptions_sp() RETURNS TABLE ("SessionSubscriptionID" integer,"SubscriptionIdentity" text,"SessionID" integer,"SubscriberSessionKey" text,"EventType" text,"DeliveryMode" text,"CallbackUrl" text,"IsEnabled" boolean,"ExpirationUtc" timestamp,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_subscription_rows() ORDER BY "SessionSubscriptionID" ASC; $$;

CREATE OR REPLACE FUNCTION copy_session_subscription_sp(p_session_subscription_id integer)
RETURNS TABLE ("SessionSubscriptionID" integer) LANGUAGE sql AS $$
	INSERT INTO session_subscriptions(subscription_identity,session_id,subscriber_session_key,event_type,delivery_mode,callback_url,is_enabled,expiration_utc,date_created,last_updated,data)
	SELECT subscription_identity || ' - Copy',session_id,subscriber_session_key,event_type,delivery_mode,callback_url,is_enabled,expiration_utc,now(),now(),data
	FROM session_subscriptions WHERE session_subscription_id=p_session_subscription_id
	RETURNING session_subscription_id;
$$;

CREATE OR REPLACE FUNCTION get_session_subscription_by_subscription_identity_sp(p_subscription_identity text) RETURNS TABLE ("SessionSubscriptionID" integer,"SubscriptionIdentity" text,"SessionID" integer,"SubscriberSessionKey" text,"EventType" text,"DeliveryMode" text,"CallbackUrl" text,"IsEnabled" boolean,"ExpirationUtc" timestamp,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_subscription_rows() WHERE "SubscriptionIdentity"=p_subscription_identity; $$;
CREATE OR REPLACE FUNCTION mark_session_subscription_as_enabled_sp(p_session_subscription_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE session_subscriptions SET is_enabled=true,last_updated=now() WHERE session_subscription_id=p_session_subscription_id; $$;
CREATE OR REPLACE FUNCTION mark_session_subscription_as_not_enabled_sp(p_session_subscription_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE session_subscriptions SET is_enabled=false,last_updated=now() WHERE session_subscription_id=p_session_subscription_id; $$;
CREATE OR REPLACE FUNCTION update_session_subscription_data_sp(p_session_subscription_id integer,p_data text) RETURNS void LANGUAGE sql AS $$ UPDATE session_subscriptions SET data=p_data,last_updated=now() WHERE session_subscription_id=p_session_subscription_id; $$;
CREATE OR REPLACE FUNCTION get_session_subscriptions_by_session_id_sp(p_session_id integer) RETURNS TABLE ("SessionSubscriptionID" integer,"SubscriptionIdentity" text,"SessionID" integer,"SubscriberSessionKey" text,"EventType" text,"DeliveryMode" text,"CallbackUrl" text,"IsEnabled" boolean,"ExpirationUtc" timestamp,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_subscription_rows() WHERE "SessionID"=p_session_id ORDER BY "SessionSubscriptionID" ASC; $$;
CREATE OR REPLACE FUNCTION get_session_subscriptions_by_subscriber_session_key_sp(p_subscriber_session_key text) RETURNS TABLE ("SessionSubscriptionID" integer,"SubscriptionIdentity" text,"SessionID" integer,"SubscriberSessionKey" text,"EventType" text,"DeliveryMode" text,"CallbackUrl" text,"IsEnabled" boolean,"ExpirationUtc" timestamp,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_subscription_rows() WHERE "SubscriberSessionKey"=p_subscriber_session_key ORDER BY "SessionSubscriptionID" ASC; $$;

CREATE OR REPLACE FUNCTION session_subscription_search_match(p_subscription session_subscriptions,p_search text) RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
	SELECT p_subscription.session_subscription_id::text ILIKE '%'||COALESCE(p_search,'')||'%'
		OR p_subscription.subscription_identity ILIKE '%'||COALESCE(p_search,'')||'%'
		OR p_subscription.subscriber_session_key ILIKE '%'||COALESCE(p_search,'')||'%'
		OR p_subscription.event_type ILIKE '%'||COALESCE(p_search,'')||'%'
		OR p_subscription.delivery_mode ILIKE '%'||COALESCE(p_search,'')||'%'
		OR COALESCE(p_subscription.callback_url,'') ILIKE '%'||COALESCE(p_search,'')||'%';
$$;

CREATE OR REPLACE FUNCTION get_session_subscriptions_sp_count_sp(p_search text) RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$
	SELECT COUNT(*)::integer FROM session_subscriptions s WHERE session_subscription_search_match(s, p_search);
$$;

CREATE OR REPLACE FUNCTION get_session_subscriptions_sp_paging_sp(p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer)
RETURNS TABLE ("SessionSubscriptionID" integer,"SubscriptionIdentity" text,"SessionID" integer,"SubscriberSessionKey" text,"EventType" text,"DeliveryMode" text,"CallbackUrl" text,"IsEnabled" boolean,"ExpirationUtc" timestamp,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$
	SELECT * FROM get_session_subscription_rows() rows
	WHERE EXISTS (SELECT 1 FROM session_subscriptions s WHERE s.session_subscription_id=rows."SessionSubscriptionID" AND session_subscription_search_match(s, p_search))
	ORDER BY
		CASE WHEN p_sort_column='SessionSubscriptionID' AND p_sort_ascending THEN "SessionSubscriptionID" END ASC,
		CASE WHEN p_sort_column='SessionSubscriptionID' AND NOT p_sort_ascending THEN "SessionSubscriptionID" END DESC,
		CASE WHEN p_sort_column='SubscriptionIdentity' AND p_sort_ascending THEN "SubscriptionIdentity" END ASC,
		CASE WHEN p_sort_column='SubscriptionIdentity' AND NOT p_sort_ascending THEN "SubscriptionIdentity" END DESC,
		CASE WHEN p_sort_column='SessionID' AND p_sort_ascending THEN "SessionID" END ASC,
		CASE WHEN p_sort_column='SessionID' AND NOT p_sort_ascending THEN "SessionID" END DESC,
		CASE WHEN p_sort_column='SubscriberSessionKey' AND p_sort_ascending THEN "SubscriberSessionKey" END ASC,
		CASE WHEN p_sort_column='SubscriberSessionKey' AND NOT p_sort_ascending THEN "SubscriberSessionKey" END DESC,
		CASE WHEN p_sort_column='EventType' AND p_sort_ascending THEN "EventType" END ASC,
		CASE WHEN p_sort_column='EventType' AND NOT p_sort_ascending THEN "EventType" END DESC,
		CASE WHEN p_sort_column='DeliveryMode' AND p_sort_ascending THEN "DeliveryMode" END ASC,
		CASE WHEN p_sort_column='DeliveryMode' AND NOT p_sort_ascending THEN "DeliveryMode" END DESC,
		CASE WHEN p_sort_column='CallbackUrl' AND p_sort_ascending THEN "CallbackUrl" END ASC,
		CASE WHEN p_sort_column='CallbackUrl' AND NOT p_sort_ascending THEN "CallbackUrl" END DESC,
		CASE WHEN p_sort_column='IsEnabled' AND p_sort_ascending THEN "IsEnabled" END ASC,
		CASE WHEN p_sort_column='IsEnabled' AND NOT p_sort_ascending THEN "IsEnabled" END DESC,
		CASE WHEN p_sort_column='ExpirationUtc' AND p_sort_ascending THEN "ExpirationUtc" END ASC,
		CASE WHEN p_sort_column='ExpirationUtc' AND NOT p_sort_ascending THEN "ExpirationUtc" END DESC,
		CASE WHEN p_sort_column='DateCreated' AND p_sort_ascending THEN "DateCreated" END ASC,
		CASE WHEN p_sort_column='DateCreated' AND NOT p_sort_ascending THEN "DateCreated" END DESC,
		CASE WHEN p_sort_column='LastUpdated' AND p_sort_ascending THEN "LastUpdated" END ASC,
		CASE WHEN p_sort_column='LastUpdated' AND NOT p_sort_ascending THEN "LastUpdated" END DESC,
		CASE WHEN p_sort_column='Data' AND p_sort_ascending THEN "Data" END ASC,
		CASE WHEN p_sort_column='Data' AND NOT p_sort_ascending THEN "Data" END DESC,
		"SessionSubscriptionID" ASC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;

CREATE OR REPLACE FUNCTION get_session_subscriptions_by_session_idsp_count_sp(p_session_id integer,p_search text) RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$
	SELECT COUNT(*)::integer FROM session_subscriptions s WHERE s.session_id=p_session_id AND session_subscription_search_match(s, p_search);
$$;

CREATE OR REPLACE FUNCTION get_session_subscriptions_by_session_idsp_paging_sp(p_session_id integer,p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer)
RETURNS TABLE ("SessionSubscriptionID" integer,"SubscriptionIdentity" text,"SessionID" integer,"SubscriberSessionKey" text,"EventType" text,"DeliveryMode" text,"CallbackUrl" text,"IsEnabled" boolean,"ExpirationUtc" timestamp,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$
	SELECT * FROM get_session_subscription_rows() rows
	WHERE "SessionID"=p_session_id AND EXISTS (SELECT 1 FROM session_subscriptions s WHERE s.session_subscription_id=rows."SessionSubscriptionID" AND session_subscription_search_match(s, p_search))
	ORDER BY
		CASE WHEN p_sort_column='SessionSubscriptionID' AND p_sort_ascending THEN "SessionSubscriptionID" END ASC,
		CASE WHEN p_sort_column='SessionSubscriptionID' AND NOT p_sort_ascending THEN "SessionSubscriptionID" END DESC,
		CASE WHEN p_sort_column='SubscriptionIdentity' AND p_sort_ascending THEN "SubscriptionIdentity" END ASC,
		CASE WHEN p_sort_column='SubscriptionIdentity' AND NOT p_sort_ascending THEN "SubscriptionIdentity" END DESC,
		CASE WHEN p_sort_column='SessionID' AND p_sort_ascending THEN "SessionID" END ASC,
		CASE WHEN p_sort_column='SessionID' AND NOT p_sort_ascending THEN "SessionID" END DESC,
		CASE WHEN p_sort_column='SubscriberSessionKey' AND p_sort_ascending THEN "SubscriberSessionKey" END ASC,
		CASE WHEN p_sort_column='SubscriberSessionKey' AND NOT p_sort_ascending THEN "SubscriberSessionKey" END DESC,
		CASE WHEN p_sort_column='EventType' AND p_sort_ascending THEN "EventType" END ASC,
		CASE WHEN p_sort_column='EventType' AND NOT p_sort_ascending THEN "EventType" END DESC,
		CASE WHEN p_sort_column='DeliveryMode' AND p_sort_ascending THEN "DeliveryMode" END ASC,
		CASE WHEN p_sort_column='DeliveryMode' AND NOT p_sort_ascending THEN "DeliveryMode" END DESC,
		CASE WHEN p_sort_column='CallbackUrl' AND p_sort_ascending THEN "CallbackUrl" END ASC,
		CASE WHEN p_sort_column='CallbackUrl' AND NOT p_sort_ascending THEN "CallbackUrl" END DESC,
		CASE WHEN p_sort_column='IsEnabled' AND p_sort_ascending THEN "IsEnabled" END ASC,
		CASE WHEN p_sort_column='IsEnabled' AND NOT p_sort_ascending THEN "IsEnabled" END DESC,
		CASE WHEN p_sort_column='ExpirationUtc' AND p_sort_ascending THEN "ExpirationUtc" END ASC,
		CASE WHEN p_sort_column='ExpirationUtc' AND NOT p_sort_ascending THEN "ExpirationUtc" END DESC,
		CASE WHEN p_sort_column='DateCreated' AND p_sort_ascending THEN "DateCreated" END ASC,
		CASE WHEN p_sort_column='DateCreated' AND NOT p_sort_ascending THEN "DateCreated" END DESC,
		CASE WHEN p_sort_column='LastUpdated' AND p_sort_ascending THEN "LastUpdated" END ASC,
		CASE WHEN p_sort_column='LastUpdated' AND NOT p_sort_ascending THEN "LastUpdated" END DESC,
		CASE WHEN p_sort_column='Data' AND p_sort_ascending THEN "Data" END ASC,
		CASE WHEN p_sort_column='Data' AND NOT p_sort_ascending THEN "Data" END DESC,
		"SessionSubscriptionID" ASC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;


SELECT record_schema_migration('008_session_subscriptions_repository_routines');

