-- Atomic authoritative movement of one exact tool-call/result pair.
ALTER TABLE turn_mutation_receipts ADD COLUMN IF NOT EXISTS maintenance_second_message_key text NULL;
ALTER TABLE turn_mutation_receipts DROP CONSTRAINT IF EXISTS ck_turn_receipt_kind;
ALTER TABLE turn_mutation_receipts ADD CONSTRAINT ck_turn_receipt_kind CHECK (mutation_kind IN ('Begin','Append','UpdateExistingMessage','Pause','Resume','Handoff','Finish','Interrupt','Compaction','Clear','HistoricalImport','MoveMessageEpoch','MoveToolPairEpoch'));

CREATE OR REPLACE FUNCTION "Turns_MoveToolPairEpoch"(
 p_session_id integer,p_operation_key uuid,p_history_generation bigint,p_owner_turn_key text,p_writer_token uuid,
 p_tool_call_message_key text,p_tool_result_message_key text,p_source_epoch integer,p_source_epoch_key text,p_target_epoch_key text,p_request_payload bytea)
RETURNS SETOF authoritative_message_epoch_receipt_rows LANGUAGE plpgsql AS $$
DECLARE session_state session_turn_state%ROWTYPE; owner_turn turns%ROWTYPE; prior turn_mutation_receipts%ROWTYPE; call_row messages%ROWTYPE; result_row messages%ROWTYPE; message_turn turns%ROWTYPE; owner_identity bytea; now_utc timestamp:=timezone('utc',clock_timestamp());
BEGIN
 IF p_session_id IS NULL OR p_session_id<=0 OR p_operation_key IS NULL OR p_operation_key='00000000-0000-0000-0000-000000000000'::uuid OR p_history_generation IS NULL OR p_history_generation<1 OR p_writer_token IS NULL OR p_writer_token='00000000-0000-0000-0000-000000000000'::uuid OR p_source_epoch IS NULL OR p_source_epoch<0 OR p_owner_turn_key IS NULL OR length(p_owner_turn_key)=0 OR p_tool_call_message_key IS NULL OR length(p_tool_call_message_key)=0 OR p_tool_result_message_key IS NULL OR length(p_tool_result_message_key)=0 OR p_tool_call_message_key COLLATE "C"=p_tool_result_message_key COLLATE "C" OR p_source_epoch_key IS NULL OR length(p_source_epoch_key)=0 OR p_target_epoch_key IS NULL OR length(p_target_epoch_key)=0 OR p_request_payload IS NULL OR octet_length(p_request_payload)=0 THEN RAISE EXCEPTION 'Invalid tool pair authority coordinates.'; END IF;
 owner_identity:=authoritative_turn_identity(p_owner_turn_key);PERFORM authoritative_turn_identity(p_tool_call_message_key);PERFORM authoritative_turn_identity(p_tool_result_message_key);
 PERFORM 1 FROM sessions WHERE session_id=p_session_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Session does not exist.';END IF;
 SELECT * INTO session_state FROM session_turn_state WHERE session_id=p_session_id FOR UPDATE;
 IF NOT FOUND OR session_state.authority_status<>'Authoritative' OR session_state.authority_contract_version<>1 OR session_state.writer_fence OR session_state.history_generation<>p_history_generation OR session_state.active_turn_identity IS DISTINCT FROM owner_identity THEN RAISE EXCEPTION 'Tool pair session generation or owner conflict.';END IF;
 SELECT * INTO owner_turn FROM turns WHERE session_id=p_session_id AND turn_identity=owner_identity AND writer_token=p_writer_token AND is_deleted=false AND state IN ('InProgress','Paused') FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Tool pair writer token conflict.';END IF;
 SELECT * INTO prior FROM turn_mutation_receipts WHERE session_id=p_session_id AND operation_key=p_operation_key;
 IF FOUND THEN
  IF prior.mutation_kind IS DISTINCT FROM 'MoveToolPairEpoch' OR prior.is_tombstone IS DISTINCT FROM false OR prior.result_history_generation IS DISTINCT FROM p_history_generation OR prior.request_payload IS DISTINCT FROM p_request_payload OR prior.message_key COLLATE "C" IS DISTINCT FROM p_tool_call_message_key COLLATE "C" OR prior.maintenance_second_message_key COLLATE "C" IS DISTINCT FROM p_tool_result_message_key COLLATE "C" OR prior.maintenance_owner_turn_key COLLATE "C" IS DISTINCT FROM p_owner_turn_key COLLATE "C" OR prior.maintenance_writer_token IS DISTINCT FROM p_writer_token OR prior.maintenance_source_epoch IS DISTINCT FROM p_source_epoch OR prior.maintenance_source_epoch_key COLLATE "C" IS DISTINCT FROM p_source_epoch_key COLLATE "C" OR prior.maintenance_target_epoch IS DISTINCT FROM p_source_epoch OR prior.maintenance_target_epoch_key COLLATE "C" IS DISTINCT FROM p_target_epoch_key COLLATE "C" THEN RAISE EXCEPTION 'Tool pair replay conflict.';END IF;
  RETURN QUERY SELECT p_operation_key,p_history_generation,2,true;RETURN;
 END IF;
 SELECT * INTO call_row FROM messages WHERE session_id=p_session_id AND message_key COLLATE "C"=p_tool_call_message_key COLLATE "C" FOR UPDATE;
 SELECT * INTO result_row FROM messages WHERE session_id=p_session_id AND message_key COLLATE "C"=p_tool_result_message_key COLLATE "C" FOR UPDATE;
 IF call_row.message_id IS NULL OR result_row.message_id IS NULL OR call_row.role COLLATE "C"<>'ToolCall' OR result_row.role COLLATE "C"<>'Tools' OR call_row.turn_id COLLATE "C"<>result_row.turn_id COLLATE "C" OR call_row.call_id IS NULL OR length(call_row.call_id)=0 OR call_row.call_id COLLATE "C"<>result_row.call_id COLLATE "C" OR call_row.compaction_epoch<>p_source_epoch OR result_row.compaction_epoch<>p_source_epoch OR call_row.compaction_epoch_key COLLATE "C"<>p_source_epoch_key COLLATE "C" OR result_row.compaction_epoch_key COLLATE "C"<>p_source_epoch_key COLLATE "C" THEN RAISE EXCEPTION 'Exact source tool pair not found.';END IF;
 SELECT * INTO message_turn FROM turns WHERE session_id=p_session_id AND turn_key COLLATE "C"=call_row.turn_id COLLATE "C" AND is_deleted=false;IF NOT FOUND THEN RAISE EXCEPTION 'Tool pair authoritative Turn does not exist.';END IF;
 UPDATE messages SET compaction_epoch_key=p_target_epoch_key WHERE message_id IN(call_row.message_id,result_row.message_id);IF NOT FOUND THEN RAISE EXCEPTION 'Tool pair update failed.';END IF;
 INSERT INTO turn_mutation_receipts(session_id,operation_key,turn_key,turn_identity,mutation_kind,request_fingerprint,request_payload,message_id,message_key,mutation_version,change_revision,occurred_at_utc,persisted_at_utc,is_tombstone,result_history_generation,maintenance_owner_turn_key,maintenance_writer_token,maintenance_source_epoch,maintenance_source_epoch_key,maintenance_target_epoch,maintenance_target_epoch_key,maintenance_second_message_key)
 VALUES(p_session_id,p_operation_key,message_turn.turn_key,message_turn.turn_identity,'MoveToolPairEpoch',sha256(p_request_payload),p_request_payload,call_row.message_id,p_tool_call_message_key,message_turn.mutation_version,message_turn.change_revision,now_utc,now_utc,false,p_history_generation,p_owner_turn_key,p_writer_token,p_source_epoch,p_source_epoch_key,p_source_epoch,p_target_epoch_key,p_tool_result_message_key);
 RETURN QUERY SELECT p_operation_key,p_history_generation,2,false;
END $$;
SELECT record_schema_migration('024_authoritative_turns_tool_pair_maintenance');
