-- Supersede authoritative Turns with the ordinary nine-column query index.
DO $$ DECLARE item record; BEGIN
	IF to_regclass(current_schema()||'.turns') IS NOT NULL AND EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='turns' AND column_name='order_key') THEN
		IF to_regclass(current_schema()||'.authoritative_turns_rollback_20260916') IS NULL THEN
			ALTER TABLE turns RENAME TO authoritative_turns_rollback_20260916;
			FOR item IN SELECT indexname FROM pg_indexes WHERE schemaname=current_schema() AND tablename='authoritative_turns_rollback_20260916'
			LOOP EXECUTE format('ALTER INDEX %I RENAME TO %I',item.indexname,'atrb16_'||substr(md5(item.indexname),1,12)); END LOOP;
		END IF;
	END IF;
END $$;
CREATE TABLE IF NOT EXISTS turns(
	turn_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id integer NOT NULL,
	turn_key text NOT NULL,
	display_order_at_utc timestamp without time zone NOT NULL,
	first_message_id integer NULL,
	user_message_id integer NULL,
	assistant_message_id integer NULL,
	last_error_message_id integer NULL,
	terminal_message_id integer NULL,
	CONSTRAINT uq_turns_session_key UNIQUE(session_id,turn_key),
	CONSTRAINT ck_turns_key CHECK(length(turn_key)>0)
);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS turn_row_id bigint NULL;
-- Session-level lifecycle events have no turn; the retired 027 migration no longer supplies this contract.
ALTER TABLE messages ALTER COLUMN turn_id DROP NOT NULL;
CREATE INDEX IF NOT EXISTS ix_turns_page ON turns(session_id,display_order_at_utc DESC,first_message_id DESC);
CREATE INDEX IF NOT EXISTS ix_messages_turn_row ON messages(session_id,turn_row_id,date_created DESC,message_id DESC);
CREATE INDEX IF NOT EXISTS ix_messages_unindexed_turn ON messages(session_id,message_id) INCLUDE(turn_id,role,date_created) WHERE turn_row_id IS NULL AND turn_id IS NOT NULL;
DO $$ DECLARE pair text[]; BEGIN
	FOREACH pair SLICE 1 IN ARRAY ARRAY[
		['session_turn_state','authoritative_turns_rollback_session_turn_state'],
		['turn_mutation_receipts','authoritative_turns_rollback_mutation_receipts'],
		['authoritative_turns_migration_checkpoint','authoritative_turns_rollback_migration_checkpoint'],
		['authoritative_turns_migration_group','authoritative_turns_rollback_migration_group'],
		['authoritative_turns_migration_exception','authoritative_turns_rollback_migration_exception'],
		['authoritative_turns_contract_artifacts','authoritative_turns_rollback_contract_artifacts']]
	LOOP
		IF to_regclass(current_schema()||'.'||pair[1]) IS NOT NULL AND to_regclass(current_schema()||'.'||pair[2]) IS NULL THEN EXECUTE format('ALTER TABLE %I RENAME TO %I',pair[1],pair[2]); END IF;
	END LOOP;
END $$;

-- Retain authority audit tables under archive names, but remove their active FK
-- dependencies and callable runtime surface.
DO $$ DECLARE item record; BEGIN
	FOR item IN SELECT conrelid::regclass AS table_name,conname FROM pg_constraint WHERE contype='f' AND conrelid::regclass::text LIKE 'authoritative_turns_rollback_%'
	LOOP EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I',item.table_name,item.conname);END LOOP;
END $$;
DROP FUNCTION IF EXISTS turns_apply_mutation CASCADE;
DROP FUNCTION IF EXISTS turns_require_authority CASCADE;
DROP FUNCTION IF EXISTS turns_read_page CASCADE;
DROP FUNCTION IF EXISTS turns_read_changes CASCADE;
DROP FUNCTION IF EXISTS turns_read_detail CASCADE;
DROP FUNCTION IF EXISTS turns_read_maintenance_generation CASCADE;
DROP FUNCTION IF EXISTS turns_move_message_epoch CASCADE;
DROP FUNCTION IF EXISTS turns_move_tool_pair_epoch CASCADE;
DROP FUNCTION IF EXISTS turns_persist_session_compaction CASCADE;
DROP FUNCTION IF EXISTS turns_read_active_process_owner CASCADE;
DROP FUNCTION IF EXISTS turns_begin_after_ended_execution CASCADE;
DROP FUNCTION IF EXISTS turns_read_pending_handoffs CASCADE;
DROP FUNCTION IF EXISTS turns_read_pending_publications CASCADE;

CREATE OR REPLACE FUNCTION turns_json(p_data text) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE AS $$ BEGIN RETURN p_data::jsonb; EXCEPTION WHEN invalid_text_representation THEN RETURN '{}'::jsonb; END $$;
CREATE OR REPLACE FUNCTION turns_outcome_state(p_data text) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT turns_json(p_data)#>>'{TerminalOutcome,State}' $$;
CREATE OR REPLACE FUNCTION turns_is_error(p_data text) RETURNS boolean LANGUAGE sql IMMUTABLE AS $$ SELECT CASE WHEN turns_outcome_state(p_data) IS NOT NULL THEN lower(turns_outcome_state(p_data))='failed' ELSE lower(COALESCE(turns_json(p_data)->>'Name',''))='error' OR lower(COALESCE(turns_json(p_data)->>'Phase',''))='error' END $$;
CREATE OR REPLACE FUNCTION turns_is_terminal(p_data text) RETURNS boolean LANGUAGE sql IMMUTABLE AS $$ SELECT CASE WHEN turns_outcome_state(p_data) IS NOT NULL THEN lower(turns_outcome_state(p_data)) IN('completed','failed','cancelled') ELSE lower(COALESCE(turns_json(p_data)->>'Name','')) IN('error','turncomplete','turncompleted') OR lower(COALESCE(turns_json(p_data)->>'Phase','')) IN('error','turncomplete','turncompleted') END $$;

CREATE OR REPLACE FUNCTION insert_message_sp(p_session_id integer,p_sequence_number integer,p_role text,p_content text,p_tool_name text,p_tool_arguments text,p_call_id text,p_data text,p_is_compacted boolean,p_compaction_epoch integer,p_message_key text,p_turn_id text,p_compaction_epoch_key text,p_date_created timestamp DEFAULT NULL)
RETURNS TABLE("MessageID" integer) LANGUAGE plpgsql AS $$
DECLARE resolved_turn_id bigint; inserted_message_id integer; occurred_at timestamp:=COALESCE(p_date_created,timezone('utc',clock_timestamp()));
BEGIN
	IF NULLIF(p_turn_id,'') IS NOT NULL THEN
		SELECT turn_id INTO resolved_turn_id FROM turns WHERE session_id=p_session_id AND turn_key=p_turn_id;
		IF resolved_turn_id IS NULL THEN
			INSERT INTO turns(session_id,turn_key,display_order_at_utc) VALUES(p_session_id,p_turn_id,occurred_at) ON CONFLICT(session_id,turn_key) DO NOTHING RETURNING turn_id INTO resolved_turn_id;
			IF resolved_turn_id IS NULL THEN SELECT turn_id INTO STRICT resolved_turn_id FROM turns WHERE session_id=p_session_id AND turn_key=p_turn_id; END IF;
		END IF;
	END IF;
	INSERT INTO messages(session_id,sequence_number,role,content,tool_name,tool_arguments,call_id,date_created,last_updated,data,is_compacted,compaction_epoch,message_key,turn_id,turn_row_id,compaction_epoch_key)
	VALUES(p_session_id,p_sequence_number,p_role,p_content,p_tool_name,p_tool_arguments,p_call_id,occurred_at,timezone('utc',clock_timestamp()),p_data,p_is_compacted,p_compaction_epoch,p_message_key,p_turn_id,resolved_turn_id,p_compaction_epoch_key) RETURNING message_id INTO inserted_message_id;
	IF resolved_turn_id IS NOT NULL THEN
		UPDATE turns t SET
			first_message_id=CASE WHEN t.first_message_id IS NULL OR(occurred_at,inserted_message_id)<((SELECT m.date_created FROM messages m WHERE m.message_id=t.first_message_id),t.first_message_id)THEN inserted_message_id ELSE t.first_message_id END,
			user_message_id=CASE WHEN p_role='User' AND(t.user_message_id IS NULL OR(occurred_at,inserted_message_id)<((SELECT m.date_created FROM messages m WHERE m.message_id=t.user_message_id),t.user_message_id))THEN inserted_message_id ELSE t.user_message_id END,
			assistant_message_id=CASE WHEN p_role='Assistant' AND(t.assistant_message_id IS NULL OR(occurred_at,inserted_message_id)>((SELECT m.date_created FROM messages m WHERE m.message_id=t.assistant_message_id),t.assistant_message_id))THEN inserted_message_id ELSE t.assistant_message_id END,
			last_error_message_id=CASE WHEN p_role='Lifecycle' AND turns_is_error(p_data) AND(t.last_error_message_id IS NULL OR(occurred_at,inserted_message_id)>((SELECT m.date_created FROM messages m WHERE m.message_id=t.last_error_message_id),t.last_error_message_id))THEN inserted_message_id ELSE t.last_error_message_id END,
			terminal_message_id=CASE WHEN p_role='Lifecycle' AND turns_is_terminal(p_data) AND(t.terminal_message_id IS NULL OR(occurred_at,inserted_message_id)>((SELECT m.date_created FROM messages m WHERE m.message_id=t.terminal_message_id),t.terminal_message_id))THEN inserted_message_id ELSE t.terminal_message_id END,
			display_order_at_utc=CASE WHEN p_role='User' AND(t.user_message_id IS NULL OR(occurred_at,inserted_message_id)<((SELECT m.date_created FROM messages m WHERE m.message_id=t.user_message_id),t.user_message_id))THEN occurred_at WHEN p_role<>'User' AND t.user_message_id IS NULL AND(t.first_message_id IS NULL OR(occurred_at,inserted_message_id)<((SELECT m.date_created FROM messages m WHERE m.message_id=t.first_message_id),t.first_message_id))THEN occurred_at ELSE t.display_order_at_utc END
		WHERE t.turn_id=resolved_turn_id;
	END IF;
	RETURN QUERY SELECT inserted_message_id;
END $$;

CREATE OR REPLACE FUNCTION update_message_sp(p_message_id integer,p_session_id integer,p_sequence_number integer,p_role text,p_content text,p_tool_name text,p_tool_arguments text,p_call_id text,p_data text,p_is_compacted boolean,p_compaction_epoch integer,p_message_key text,p_thread_key text,p_compaction_epoch_key text)
RETURNS void LANGUAGE plpgsql AS $$ DECLARE resolved_turn_id bigint; occurred_at timestamp; BEGIN SELECT date_created INTO occurred_at FROM messages WHERE message_id=p_message_id; IF NOT FOUND THEN RETURN; END IF; IF NULLIF(p_thread_key,'') IS NOT NULL THEN INSERT INTO turns(session_id,turn_key,display_order_at_utc) VALUES(p_session_id,p_thread_key,occurred_at) ON CONFLICT(session_id,turn_key) DO NOTHING RETURNING turn_id INTO resolved_turn_id; IF resolved_turn_id IS NULL THEN SELECT turn_id INTO STRICT resolved_turn_id FROM turns WHERE session_id=p_session_id AND turn_key=p_thread_key; END IF; END IF; UPDATE messages SET session_id=p_session_id,sequence_number=p_sequence_number,role=p_role,content=p_content,tool_name=p_tool_name,tool_arguments=p_tool_arguments,call_id=p_call_id,last_updated=timezone('utc',clock_timestamp()),data=p_data,is_compacted=p_is_compacted,compaction_epoch=p_compaction_epoch,message_key=p_message_key,turn_id=p_thread_key,turn_row_id=resolved_turn_id,compaction_epoch_key=p_compaction_epoch_key WHERE message_id=p_message_id; END $$;
CREATE OR REPLACE FUNCTION update_message_compaction_epoch_atomic_sp(p_session_id integer,p_message_key text,p_compaction_epoch integer,p_compaction_epoch_key text) RETURNS TABLE("UpdatedRows" integer) LANGUAGE plpgsql AS $$ DECLARE affected integer; BEGIN UPDATE messages SET compaction_epoch=p_compaction_epoch,compaction_epoch_key=p_compaction_epoch_key,last_updated=timezone('utc',clock_timestamp()) WHERE session_id=p_session_id AND message_key=p_message_key AND (compaction_epoch IS DISTINCT FROM p_compaction_epoch OR compaction_epoch_key IS DISTINCT FROM p_compaction_epoch_key); GET DIAGNOSTICS affected=ROW_COUNT; RETURN QUERY SELECT affected; END $$;
CREATE OR REPLACE FUNCTION update_tool_result_pair_compaction_epoch_key_atomic_sp(p_session_id integer,p_tool_call_message_key text,p_tool_result_message_key text,p_source_compaction_epoch integer,p_source_compaction_epoch_key text,p_target_compaction_epoch_key text) RETURNS TABLE("UpdatedRows" integer) LANGUAGE plpgsql AS $$ DECLARE affected integer; BEGIN UPDATE messages SET compaction_epoch_key=p_target_compaction_epoch_key,last_updated=timezone('utc',clock_timestamp()) WHERE session_id=p_session_id AND compaction_epoch=p_source_compaction_epoch AND compaction_epoch_key=p_source_compaction_epoch_key AND ((message_key=p_tool_call_message_key AND role='ToolCall') OR(message_key=p_tool_result_message_key AND role='Tools')) AND 2=(SELECT count(*) FROM messages WHERE session_id=p_session_id AND compaction_epoch=p_source_compaction_epoch AND compaction_epoch_key=p_source_compaction_epoch_key AND ((message_key=p_tool_call_message_key AND role='ToolCall') OR(message_key=p_tool_result_message_key AND role='Tools'))); GET DIAGNOSTICS affected=ROW_COUNT; RETURN QUERY SELECT affected; END $$;
CREATE OR REPLACE FUNCTION update_message_data_sp(p_message_id integer,p_data text) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET data=p_data,last_updated=timezone('utc',clock_timestamp()) WHERE message_id=p_message_id $$;
CREATE OR REPLACE FUNCTION update_message_tool_arguments_sp(p_message_id integer,p_tool_arguments text) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET tool_arguments=p_tool_arguments,last_updated=timezone('utc',clock_timestamp()) WHERE message_id=p_message_id $$;
CREATE OR REPLACE FUNCTION update_message_date_created_sp(p_message_id integer,p_date_created timestamp) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET date_created=p_date_created WHERE message_id=p_message_id $$;
CREATE OR REPLACE FUNCTION remove_message_sp(p_message_id integer) RETURNS void LANGUAGE sql AS $$ DELETE FROM messages WHERE message_id=p_message_id $$;
CREATE OR REPLACE FUNCTION copy_message_sp(p_message_id integer) RETURNS TABLE("MessageID" integer) LANGUAGE plpgsql AS $$
DECLARE source_row messages%ROWTYPE;
BEGIN
	SELECT * INTO source_row FROM messages WHERE message_id=p_message_id;
	-- The pre-authority provider returned no rows for a missing source.
	IF NOT FOUND THEN RETURN; END IF;
	-- Resolve the provider-local index exactly as an ordinary insert; never copy a stale numeric link.
	RETURN QUERY SELECT * FROM insert_message_sp(source_row.session_id,source_row.sequence_number,source_row.role,source_row.content,
		source_row.tool_name,source_row.tool_arguments,source_row.call_id,source_row.data,source_row.is_compacted,source_row.compaction_epoch,
		source_row.message_key||'-copy-'||replace(clock_timestamp()::text,' ','-')||'-'||floor(random()*1000000)::integer::text,
		source_row.turn_id,source_row.compaction_epoch_key,timezone('utc',clock_timestamp()));
END $$;
CREATE OR REPLACE FUNCTION mark_message_as_compacted_sp(p_message_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET is_compacted=true,last_updated=timezone('utc',clock_timestamp()) WHERE message_id=p_message_id $$;
CREATE OR REPLACE FUNCTION mark_message_as_not_compacted_sp(p_message_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET is_compacted=false,last_updated=timezone('utc',clock_timestamp()) WHERE message_id=p_message_id $$;
CREATE OR REPLACE FUNCTION messages_clear_session_timeline(p_session_id integer) RETURNS TABLE("DeletedMessages" integer,"DeletedTurns" integer) LANGUAGE plpgsql AS $$ DECLARE dm integer;dt integer; BEGIN DELETE FROM messages WHERE session_id=p_session_id;GET DIAGNOSTICS dm=ROW_COUNT;DELETE FROM turns WHERE session_id=p_session_id;GET DIAGNOSTICS dt=ROW_COUNT;RETURN QUERY SELECT dm,dt;END $$;

CREATE OR REPLACE FUNCTION turns_populate_unlinked(p_session_id integer,p_max_messages integer,p_lock_timeout_milliseconds integer)
RETURNS TABLE("ProcessedMessages" integer,"HasMore" boolean) LANGUAGE plpgsql AS $$ DECLARE processed integer; BEGIN
	IF p_session_id<=0 OR p_max_messages<1 OR p_max_messages>1000 OR p_lock_timeout_milliseconds<1 OR p_lock_timeout_milliseconds>30000 THEN RAISE EXCEPTION 'Invalid Turns populate bounds.'; END IF;
	PERFORM set_config('lock_timeout',p_lock_timeout_milliseconds::text||'ms',true);
	DROP TABLE IF EXISTS pg_temp.populate_turn_messages;
	CREATE TEMP TABLE populate_turn_messages(message_id integer PRIMARY KEY,turn_key text NOT NULL) ON COMMIT DROP;
	INSERT INTO populate_turn_messages SELECT message_id,turn_id FROM messages WHERE session_id=p_session_id AND turn_row_id IS NULL AND turn_id IS NOT NULL AND turn_id<>'' ORDER BY message_id LIMIT p_max_messages;
	GET DIAGNOSTICS processed=ROW_COUNT;
	INSERT INTO turns(session_id,turn_key,display_order_at_utc) SELECT p_session_id,p.turn_key,min(m.date_created) FROM (SELECT DISTINCT turn_key FROM populate_turn_messages)p JOIN messages m ON m.session_id=p_session_id AND m.turn_id=p.turn_key GROUP BY p.turn_key ON CONFLICT(session_id,turn_key) DO NOTHING;
	UPDATE messages m SET turn_row_id=t.turn_id FROM populate_turn_messages p,turns t WHERE m.message_id=p.message_id AND m.session_id=p_session_id AND m.turn_id=p.turn_key AND m.turn_row_id IS NULL AND t.session_id=m.session_id AND t.turn_key=m.turn_id;
	UPDATE turns t SET display_order_at_utc=COALESCE(q.user_at,q.first_at),first_message_id=q.first_id,user_message_id=q.user_id,assistant_message_id=q.assistant_id,last_error_message_id=q.error_id,terminal_message_id=q.terminal_id FROM(
		SELECT p.turn_key,(array_agg(m.date_created ORDER BY m.date_created,m.message_id))[1] first_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id))[1] first_id,(array_agg(m.date_created ORDER BY m.date_created,m.message_id) FILTER(WHERE m.role='User'))[1] user_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id) FILTER(WHERE m.role='User'))[1] user_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC) FILTER(WHERE m.role='Assistant'))[1] assistant_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC) FILTER(WHERE m.role='Lifecycle' AND turns_is_error(m.data)))[1] error_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC) FILTER(WHERE m.role='Lifecycle' AND turns_is_terminal(m.data)))[1] terminal_id FROM (SELECT DISTINCT turn_key FROM populate_turn_messages)p JOIN messages m ON m.session_id=p_session_id AND m.turn_id=p.turn_key GROUP BY p.turn_key)q WHERE t.session_id=p_session_id AND t.turn_key=q.turn_key;
	RETURN QUERY SELECT processed,EXISTS(SELECT 1 FROM messages WHERE session_id=p_session_id AND turn_row_id IS NULL AND turn_id IS NOT NULL AND turn_id<>'');
END $$;

CREATE OR REPLACE FUNCTION turns_repair_page(p_session_id integer,p_after_turn_id bigint,p_num_rows integer,p_lock_timeout_milliseconds integer)
RETURNS TABLE("RepairedTurns" integer,"LastTurnID" bigint,"HasMore" boolean) LANGUAGE plpgsql AS $$ DECLARE repaired integer;last_id bigint; BEGIN
	IF p_session_id<=0 OR p_after_turn_id<0 OR p_num_rows<1 OR p_num_rows>1000 OR p_lock_timeout_milliseconds<1 OR p_lock_timeout_milliseconds>30000 THEN RAISE EXCEPTION 'Invalid Turns repair bounds.'; END IF;
	PERFORM set_config('lock_timeout',p_lock_timeout_milliseconds::text||'ms',true);
	DROP TABLE IF EXISTS pg_temp.repair_turns;
	CREATE TEMP TABLE repair_turns(turn_id bigint PRIMARY KEY,turn_key text NOT NULL) ON COMMIT DROP;
	INSERT INTO repair_turns SELECT turn_id,turn_key FROM turns WHERE session_id=p_session_id AND turn_id>p_after_turn_id ORDER BY turn_id LIMIT p_num_rows;
	GET DIAGNOSTICS repaired=ROW_COUNT; SELECT COALESCE(max(turn_id),p_after_turn_id) INTO last_id FROM repair_turns;
	DELETE FROM turns t USING repair_turns r WHERE t.turn_id=r.turn_id AND NOT EXISTS(SELECT 1 FROM messages m WHERE m.session_id=p_session_id AND m.turn_id=r.turn_key);
	UPDATE turns t SET display_order_at_utc=COALESCE(q.user_at,q.first_at),first_message_id=q.first_id,user_message_id=q.user_id,assistant_message_id=q.assistant_id,last_error_message_id=q.error_id,terminal_message_id=q.terminal_id FROM(
		SELECT r.turn_id,(array_agg(m.date_created ORDER BY m.date_created,m.message_id))[1] first_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id))[1] first_id,(array_agg(m.date_created ORDER BY m.date_created,m.message_id) FILTER(WHERE m.role='User'))[1] user_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id) FILTER(WHERE m.role='User'))[1] user_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC) FILTER(WHERE m.role='Assistant'))[1] assistant_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC) FILTER(WHERE m.role='Lifecycle' AND turns_is_error(m.data)))[1] error_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC) FILTER(WHERE m.role='Lifecycle' AND turns_is_terminal(m.data)))[1] terminal_id FROM repair_turns r JOIN messages m ON m.session_id=p_session_id AND m.turn_id=r.turn_key GROUP BY r.turn_id)q WHERE t.turn_id=q.turn_id;
	RETURN QUERY SELECT repaired,last_id,EXISTS(SELECT 1 FROM turns WHERE session_id=p_session_id AND turn_id>last_id);
END $$;

CREATE OR REPLACE FUNCTION turns_maintain_index(p_session_id integer,p_turn_keys_json text,p_max_unlinked_messages integer,p_lock_timeout_milliseconds integer) RETURNS TABLE("ProcessedMessages" integer,"RepairedTurns" integer,"HasMoreUnlinked" boolean) LANGUAGE plpgsql AS $$ DECLARE processed integer:=0;repaired integer:=0;remaining boolean:=false;BEGIN IF p_session_id<=0 OR p_max_unlinked_messages<0 OR p_max_unlinked_messages>1000 OR p_lock_timeout_milliseconds<1 OR p_lock_timeout_milliseconds>30000 OR jsonb_typeof(p_turn_keys_json::jsonb)<>'array' OR jsonb_array_length(p_turn_keys_json::jsonb)>200 THEN RAISE EXCEPTION 'Invalid Turns maintenance bounds.';END IF;PERFORM set_config('lock_timeout',p_lock_timeout_milliseconds::text||'ms',true);IF current_setting('transaction_read_only')='on' OR pg_is_in_recovery() OR NOT has_table_privilege(current_user,'messages','UPDATE') OR NOT has_table_privilege(current_user,'turns','INSERT,UPDATE,DELETE') THEN SELECT EXISTS(SELECT 1 FROM messages WHERE session_id=p_session_id AND turn_row_id IS NULL AND turn_id IS NOT NULL AND turn_id<>'') INTO remaining;RETURN QUERY SELECT processed,repaired,remaining;RETURN;END IF;IF p_max_unlinked_messages>0 THEN SELECT p."ProcessedMessages",p."HasMore" INTO processed,remaining FROM turns_populate_unlinked(p_session_id,p_max_unlinked_messages,p_lock_timeout_milliseconds)p;ELSE SELECT EXISTS(SELECT 1 FROM messages WHERE session_id=p_session_id AND turn_row_id IS NULL AND turn_id IS NOT NULL AND turn_id<>'')INTO remaining;END IF;DROP TABLE IF EXISTS pg_temp.maintenance_keys;CREATE TEMP TABLE maintenance_keys(turn_key text PRIMARY KEY)ON COMMIT DROP;INSERT INTO maintenance_keys SELECT DISTINCT value#>>'{}' FROM jsonb_array_elements(p_turn_keys_json::jsonb)value WHERE jsonb_typeof(value)='string' AND value#>>'{}'<>'';DELETE FROM turns t USING maintenance_keys k WHERE t.session_id=p_session_id AND t.turn_key=k.turn_key AND NOT EXISTS(SELECT 1 FROM messages m WHERE m.session_id=p_session_id AND m.turn_id=k.turn_key);UPDATE turns t SET display_order_at_utc=COALESCE(q.user_at,q.first_at),first_message_id=q.first_id,user_message_id=q.user_id,assistant_message_id=q.assistant_id,last_error_message_id=q.error_id,terminal_message_id=q.terminal_id FROM(SELECT k.turn_key,(array_agg(m.date_created ORDER BY m.date_created,m.message_id))[1]first_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id))[1]first_id,(array_agg(m.date_created ORDER BY m.date_created,m.message_id)FILTER(WHERE m.role='User'))[1]user_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id)FILTER(WHERE m.role='User'))[1]user_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Assistant'))[1]assistant_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Lifecycle' AND turns_is_error(m.data)))[1]error_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Lifecycle' AND turns_is_terminal(m.data)))[1]terminal_id FROM maintenance_keys k JOIN messages m ON m.session_id=p_session_id AND m.turn_id=k.turn_key GROUP BY k.turn_key)q WHERE t.session_id=p_session_id AND t.turn_key=q.turn_key;GET DIAGNOSTICS repaired=ROW_COUNT;RETURN QUERY SELECT processed,repaired,remaining;END $$;
CREATE OR REPLACE FUNCTION turns_read_index_page(p_session_id integer,p_skip_rows integer,p_num_rows integer,p_before_time timestamp,p_before_message_id integer,p_user_only boolean,p_force_message_projection boolean)
RETURNS TABLE("TotalTurns" bigint,"HasMore" boolean,"TurnID" bigint,"SessionID" integer,"TurnKey" text,"DisplayOrderAtUtc" timestamp,"FirstMessageID" integer,"UserMessageID" integer,"AssistantMessageID" integer,"LastErrorMessageID" integer,"TerminalMessageID" integer) LANGUAGE plpgsql STABLE AS $$ BEGIN
	IF p_skip_rows<0 OR p_num_rows<1 OR p_num_rows>5000 THEN RAISE EXCEPTION 'Invalid Turns index page bounds.'; END IF;
	IF (p_before_time IS NULL)<>(p_before_message_id IS NULL) THEN RAISE EXCEPTION 'Both Turns index page boundary values are required.'; END IF;
	IF NOT p_force_message_projection AND NOT EXISTS(SELECT 1 FROM messages WHERE session_id=p_session_id AND turn_row_id IS NULL AND turn_id IS NOT NULL AND turn_id<>'') THEN
		RETURN QUERY WITH complete AS(SELECT t.turn_id,t.session_id,t.turn_key,t.display_order_at_utc,t.first_message_id,t.user_message_id,t.assistant_message_id,t.last_error_message_id,t.terminal_message_id FROM turns t WHERE t.session_id=p_session_id AND(NOT p_user_only OR t.user_message_id IS NOT NULL) AND EXISTS(SELECT 1 FROM messages m WHERE m.session_id=p_session_id AND m.turn_id=t.turn_key)),filtered AS(SELECT * FROM complete WHERE p_before_time IS NULL OR display_order_at_utc<p_before_time OR(display_order_at_utc=p_before_time AND first_message_id<p_before_message_id)),counts AS(SELECT(SELECT count(*) FROM complete)total,(SELECT count(*) FROM filtered)available),page AS(SELECT * FROM filtered ORDER BY display_order_at_utc DESC,first_message_id DESC OFFSET p_skip_rows LIMIT p_num_rows) SELECT counts.total,p_skip_rows+p_num_rows<counts.available,page.* FROM counts LEFT JOIN page ON true; RETURN;
	END IF;
	RETURN QUERY WITH keys AS(SELECT DISTINCT m.turn_id turn_key FROM messages m WHERE m.session_id=p_session_id AND m.turn_id IS NOT NULL AND m.turn_id<>''),complete AS(SELECT CASE WHEN p_force_message_projection OR EXISTS(SELECT 1 FROM messages x WHERE x.session_id=p_session_id AND x.turn_id=k.turn_key AND x.turn_row_id IS NULL)THEN 0::bigint ELSE COALESCE(t.turn_id,0::bigint)END turn_id,p_session_id session_id,k.turn_key,COALESCE(q.user_at,q.first_at)display_order_at_utc,q.first_id first_message_id,q.user_id user_message_id,q.assistant_id assistant_message_id,q.error_id last_error_message_id,q.terminal_id terminal_message_id FROM keys k LEFT JOIN turns t ON t.session_id=p_session_id AND t.turn_key=k.turn_key CROSS JOIN LATERAL(SELECT(array_agg(m.date_created ORDER BY m.date_created,m.message_id))[1]first_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id))[1]first_id,(array_agg(m.date_created ORDER BY m.date_created,m.message_id)FILTER(WHERE m.role='User'))[1]user_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id)FILTER(WHERE m.role='User'))[1]user_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Assistant'))[1]assistant_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Lifecycle' AND turns_is_error(m.data)))[1]error_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Lifecycle' AND turns_is_terminal(m.data)))[1]terminal_id FROM messages m WHERE m.session_id=p_session_id AND m.turn_id=k.turn_key)q WHERE NOT p_user_only OR q.user_id IS NOT NULL),filtered AS(SELECT * FROM complete WHERE p_before_time IS NULL OR display_order_at_utc<p_before_time OR(display_order_at_utc=p_before_time AND first_message_id<p_before_message_id)),counts AS(SELECT(SELECT count(*) FROM complete)total,(SELECT count(*) FROM filtered)available),page AS(SELECT * FROM filtered ORDER BY display_order_at_utc DESC,first_message_id DESC OFFSET p_skip_rows LIMIT p_num_rows) SELECT counts.total,p_skip_rows+p_num_rows<counts.available,page.* FROM counts LEFT JOIN page ON true;
END $$;

CREATE OR REPLACE FUNCTION turns_read_index_turn(p_session_id integer,p_turn_key text,p_force_message_projection boolean) RETURNS TABLE("TurnID" bigint,"SessionID" integer,"TurnKey" text,"DisplayOrderAtUtc" timestamp,"FirstMessageID" integer,"UserMessageID" integer,"AssistantMessageID" integer,"LastErrorMessageID" integer,"TerminalMessageID" integer) LANGUAGE plpgsql STABLE AS $$ BEGIN
	IF NOT p_force_message_projection AND NOT EXISTS(SELECT 1 FROM messages WHERE session_id=p_session_id AND turn_id=p_turn_key AND turn_row_id IS NULL) AND EXISTS(SELECT 1 FROM turns t WHERE t.session_id=p_session_id AND t.turn_key=p_turn_key AND EXISTS(SELECT 1 FROM messages m WHERE m.session_id=p_session_id AND m.turn_id=p_turn_key) AND NOT EXISTS(SELECT 1 FROM unnest(ARRAY[t.first_message_id,t.user_message_id,t.assistant_message_id,t.last_error_message_id,t.terminal_message_id]) anchor_id WHERE anchor_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM messages m WHERE m.message_id=anchor_id AND m.session_id=p_session_id AND m.turn_id=p_turn_key AND m.turn_row_id=t.turn_id))) THEN RETURN QUERY SELECT t.turn_id,t.session_id,t.turn_key,t.display_order_at_utc,t.first_message_id,t.user_message_id,t.assistant_message_id,t.last_error_message_id,t.terminal_message_id FROM turns t WHERE t.session_id=p_session_id AND t.turn_key=p_turn_key; RETURN; END IF;
	RETURN QUERY WITH q AS(SELECT(array_agg(m.date_created ORDER BY m.date_created,m.message_id))[1]first_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id))[1]first_id,(array_agg(m.date_created ORDER BY m.date_created,m.message_id)FILTER(WHERE m.role='User'))[1]user_at,(array_agg(m.message_id ORDER BY m.date_created,m.message_id)FILTER(WHERE m.role='User'))[1]user_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Assistant'))[1]assistant_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Lifecycle' AND turns_is_error(m.data)))[1]error_id,(array_agg(m.message_id ORDER BY m.date_created DESC,m.message_id DESC)FILTER(WHERE m.role='Lifecycle' AND turns_is_terminal(m.data)))[1]terminal_id,count(*)row_count FROM messages m WHERE m.session_id=p_session_id AND m.turn_id=p_turn_key) SELECT 0::bigint,p_session_id,p_turn_key,COALESCE(q.user_at,q.first_at),q.first_id,q.user_id,q.assistant_id,q.error_id,q.terminal_id FROM q WHERE q.row_count>0;
END $$;

CREATE OR REPLACE FUNCTION turns_read_index_detail_rows(p_session_id integer,p_turn_key text,p_num_rows integer) RETURNS TABLE("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text,"TurnRowID" bigint) LANGUAGE sql STABLE AS $$ SELECT newest.message_id,newest.session_id,newest.sequence_number,newest.role,newest.content,newest.tool_name,newest.tool_arguments,newest.call_id,newest.date_created,newest.last_updated,newest.data,newest.is_compacted,newest.compaction_epoch,newest.message_key,newest.turn_id,newest.compaction_epoch_key,newest.turn_row_id FROM(SELECT m.message_id,m.session_id,m.sequence_number,m.role,m.content,m.tool_name,m.tool_arguments,m.call_id,m.date_created,m.last_updated,m.data,m.is_compacted,m.compaction_epoch,m.message_key,m.turn_id,m.compaction_epoch_key,m.turn_row_id FROM messages m WHERE m.session_id=p_session_id AND m.turn_id=p_turn_key ORDER BY m.date_created DESC,m.message_id DESC LIMIT p_num_rows)newest ORDER BY newest.date_created,newest.message_id $$;


-- One ordinary message transaction; an exception rolls back retained moves, new rows and session data.
CREATE OR REPLACE FUNCTION messages_persist_session_compaction(
	p_session_id integer,p_target_epoch integer,p_target_epoch_key text,p_session_data text,
	p_retained_messages_json text,p_inserted_messages_json text)
RETURNS TABLE("MovedRows" integer,"InsertedRows" integer) LANGUAGE plpgsql AS $$
DECLARE
	retained jsonb:=p_retained_messages_json::jsonb;
	inserted jsonb:=p_inserted_messages_json::jsonb;
	row_data jsonb;
	moved integer:=0;
	inserted_count integer:=0;
	next_sequence integer;
	ordinal integer:=0;
BEGIN
	IF p_session_id<=0 OR p_target_epoch<0 OR NULLIF(p_target_epoch_key,'') IS NULL
		OR p_session_data IS NULL OR jsonb_typeof(retained) IS DISTINCT FROM 'array'
		OR jsonb_typeof(inserted) IS DISTINCT FROM 'array' THEN
		RAISE EXCEPTION 'Invalid session compaction request.';
	END IF;
	PERFORM p_session_data::jsonb;
	IF NOT EXISTS(SELECT 1 FROM sessions WHERE session_id=p_session_id) THEN RAISE EXCEPTION 'Session does not exist.'; END IF;
	IF EXISTS(SELECT 1 FROM jsonb_array_elements(retained) r WHERE NULLIF(r->>'MessageKey','') IS NULL)
		OR EXISTS(SELECT 1 FROM jsonb_array_elements(inserted) n WHERE NULLIF(n->>'MessageKey','') IS NULL OR NULLIF(n->>'Role','') IS NULL OR n->>'DateCreatedUtc' IS NULL OR n->>'IsCompacted' IS NULL) THEN
		RAISE EXCEPTION 'Invalid compaction message contract.';
	END IF;
	IF EXISTS(SELECT 1 FROM jsonb_array_elements(retained) r
		LEFT JOIN messages m ON m.session_id=p_session_id AND m.message_key=r->>'MessageKey'
		WHERE m.message_id IS NULL OR NOT(
			(m.compaction_epoch IS NOT DISTINCT FROM (r->>'SourceEpoch')::integer AND m.compaction_epoch_key IS NOT DISTINCT FROM r->>'SourceEpochKey')
			OR(m.compaction_epoch IS NOT DISTINCT FROM p_target_epoch AND m.compaction_epoch_key IS NOT DISTINCT FROM p_target_epoch_key))) THEN
		RAISE EXCEPTION 'Retained message source conflict.';
	END IF;
	UPDATE messages m SET compaction_epoch=p_target_epoch,compaction_epoch_key=p_target_epoch_key
		FROM jsonb_array_elements(retained) r WHERE m.session_id=p_session_id AND m.message_key=r->>'MessageKey'
		AND(m.compaction_epoch IS DISTINCT FROM p_target_epoch OR m.compaction_epoch_key IS DISTINCT FROM p_target_epoch_key);
	GET DIAGNOSTICS moved=ROW_COUNT;
	IF EXISTS(SELECT 1 FROM jsonb_array_elements(inserted) n JOIN messages m ON m.session_id=p_session_id AND m.message_key=n->>'MessageKey'
		WHERE m.compaction_epoch IS DISTINCT FROM p_target_epoch OR m.compaction_epoch_key IS DISTINCT FROM p_target_epoch_key
		OR m.turn_id IS DISTINCT FROM n->>'TurnKey' OR m.role IS DISTINCT FROM n->>'Role' OR COALESCE(m.content,'')<>COALESCE(n->>'Content','')) THEN
		RAISE EXCEPTION 'Inserted compaction message replay conflict.';
	END IF;
	SELECT COALESCE(max(sequence_number),0) INTO next_sequence FROM messages WHERE session_id=p_session_id;
	FOR row_data IN SELECT value FROM jsonb_array_elements(inserted) LOOP
		ordinal:=ordinal+1;
		IF NOT EXISTS(SELECT 1 FROM messages WHERE session_id=p_session_id AND message_key=row_data->>'MessageKey') THEN
			PERFORM * FROM insert_message_sp(p_session_id,next_sequence+ordinal,row_data->>'Role',row_data->>'Content',row_data->>'ToolName',row_data->>'ToolArguments',row_data->>'CallID',row_data->>'Data',(row_data->>'IsCompacted')::boolean,p_target_epoch,row_data->>'MessageKey',row_data->>'TurnKey',p_target_epoch_key,(row_data->>'DateCreatedUtc')::timestamp);
			inserted_count:=inserted_count+1;
		END IF;
	END LOOP;
	UPDATE sessions SET data=p_session_data,last_updated=timezone('utc',clock_timestamp()) WHERE session_id=p_session_id;
	RETURN QUERY SELECT moved,inserted_count;
END $$;

SELECT record_schema_migration('030_turns_query_index');

