IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE Specific_Name = 'GetProcessesSp')
BEGIN
	DROP PROCEDURE GetProcessesSp
END
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[GetProcessesSp]
AS
    
    -- Automatically generated on 4/8/2026 10:11:10 AM.
    
    SELECT *
    FROM Processes WITH (NOLOCK) 
GO
