IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE Specific_Name = 'Sessions_GetArchivedSp_Sp')
BEGIN
	DROP PROCEDURE Sessions_GetArchivedSp_Sp
END
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[Sessions_GetArchivedSp_Sp]
AS

	SET NOCOUNT ON

	SELECT *
	FROM Sessions WITH (NOLOCK)
	WHERE ISNULL(IsArchived, 0) = 1
GO
