CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS embeddings (
	embedding_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	embedding_model varchar(255) NOT NULL,
	data text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_embeddings_embedding_model ON embeddings (embedding_model);

CREATE TABLE IF NOT EXISTS fragments (
	fragment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fragment text NOT NULL,
	parent_fragment_id integer NULL REFERENCES fragments(fragment_id),
	fragment_key varchar(255) NOT NULL,
	data text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_fragments_fragment_key ON fragments (fragment_key);
CREATE INDEX IF NOT EXISTS ix_fragments_parent_fragment_id ON fragments (parent_fragment_id);
CREATE INDEX IF NOT EXISTS ix_fragments_date_created ON fragments (date_created);


CREATE TABLE IF NOT EXISTS tags (
	tag_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tag_name varchar(255) NOT NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tags_tag_name ON tags (tag_name);

CREATE TABLE IF NOT EXISTS fragment_tags (
	fragment_tag_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fragment_id integer NOT NULL REFERENCES fragments(fragment_id) ON DELETE CASCADE,
	tag_id integer NOT NULL REFERENCES tags(tag_id) ON DELETE CASCADE,
	data text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_fragment_tags_fragment_id_tag_id ON fragment_tags (fragment_id, tag_id);
CREATE INDEX IF NOT EXISTS ix_fragment_tags_tag_id_fragment_id ON fragment_tags (tag_id, fragment_id);

CREATE TABLE IF NOT EXISTS fragment_vectors_native (
	fragment_id integer NOT NULL REFERENCES fragments(fragment_id) ON DELETE CASCADE,
	embedding_id integer NOT NULL REFERENCES embeddings(embedding_id) ON DELETE CASCADE,
	vector_dimensions integer NOT NULL,
	embedding_hash varchar(64) NULL,
	vector_value vector(1536) NOT NULL,
	last_embedded_utc timestamp NOT NULL DEFAULT timezone('utc', now()),
	CONSTRAINT pk_fragment_vectors_native PRIMARY KEY (fragment_id, embedding_id),
	CONSTRAINT ck_fragment_vectors_native_dimensions CHECK (vector_dimensions = 1536)
);

CREATE INDEX IF NOT EXISTS ix_fragment_vectors_native_embedding_id ON fragment_vectors_native (embedding_id, fragment_id);
CREATE INDEX IF NOT EXISTS ix_fragment_vectors_native_vector_hnsw ON fragment_vectors_native USING hnsw (vector_value vector_cosine_ops);


SELECT record_schema_migration('001_semantic_vector_schema');
