-- PostgreSQL completion-usage ledger parity: schema, idempotent write, and exact aggregate projection.

CREATE TABLE IF NOT EXISTS usage_events (
	usage_event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	usage_event_key uuid NULL,
	session_id integer NOT NULL REFERENCES sessions(session_id),
	message_id integer NULL REFERENCES messages(message_id),
	provider text NOT NULL,
	transport text NOT NULL,
	model_name text NOT NULL,
	reasoning_level text NULL,
	provider_client_type text NULL,
	credential_source text NULL,
	credential_profile_id text NULL,
	credential_display_name text NULL,
	credential_fingerprint text NULL,
	effective_base_url text NULL,
	provider_request_id text NULL,
	provider_response_id text NULL,
	input_tokens integer NOT NULL DEFAULT 0,
	output_tokens integer NOT NULL DEFAULT 0,
	reasoning_tokens integer NOT NULL DEFAULT 0,
	cached_tokens integer NOT NULL DEFAULT 0,
	total_tokens integer NOT NULL DEFAULT 0,
	latency_ms integer NOT NULL DEFAULT 0,
	usage_operation text NOT NULL,
	operation_reference_id text NULL,
	compaction_epoch integer NULL,
	compaction_epoch_key text NULL,
	provider_limit_snapshot_usage_event_id integer NULL REFERENCES usage_events(usage_event_id),
	status text NOT NULL,
	error_code text NULL,
	data text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now()
);

ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS usage_event_key uuid NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_usage_events_session_usage_event_key ON usage_events(session_id, usage_event_key) WHERE usage_event_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_usage_events_completion_ledger ON usage_events(session_id, usage_operation, status, operation_reference_id, compaction_epoch) INCLUDE (input_tokens, output_tokens, reasoning_tokens, cached_tokens, total_tokens);
CREATE INDEX IF NOT EXISTS ix_usage_events_session_id ON usage_events(session_id, usage_event_id);

CREATE OR REPLACE FUNCTION insert_usage_event_sp(
	p_session_id integer, p_message_id integer, p_provider text, p_transport text, p_model_name text,
	p_reasoning_level text, p_provider_client_type text, p_credential_source text, p_credential_profile_id text,
	p_credential_display_name text, p_credential_fingerprint text, p_effective_base_url text,
	p_provider_request_id text, p_provider_response_id text, p_input_tokens integer, p_output_tokens integer,
	p_reasoning_tokens integer, p_cached_tokens integer, p_total_tokens integer, p_latency_ms integer,
	p_usage_operation text, p_operation_reference_id text, p_compaction_epoch integer, p_compaction_epoch_key text,
	p_provider_limit_snapshot_usage_event_id integer, p_status text, p_error_code text, p_data text)
RETURNS TABLE ("UsageEventID" integer)
LANGUAGE sql AS $$
	INSERT INTO usage_events(session_id, message_id, provider, transport, model_name, reasoning_level,
		provider_client_type, credential_source, credential_profile_id, credential_display_name, credential_fingerprint,
		effective_base_url, provider_request_id, provider_response_id, input_tokens, output_tokens, reasoning_tokens,
		cached_tokens, total_tokens, latency_ms, usage_operation, operation_reference_id, compaction_epoch,
		compaction_epoch_key, provider_limit_snapshot_usage_event_id, status, error_code, data)
	VALUES(p_session_id, p_message_id, p_provider, p_transport, p_model_name, p_reasoning_level,
		p_provider_client_type, p_credential_source, p_credential_profile_id, p_credential_display_name, p_credential_fingerprint,
		p_effective_base_url, p_provider_request_id, p_provider_response_id, p_input_tokens, p_output_tokens, p_reasoning_tokens,
		p_cached_tokens, p_total_tokens, p_latency_ms, p_usage_operation, p_operation_reference_id, p_compaction_epoch,
		p_compaction_epoch_key, p_provider_limit_snapshot_usage_event_id, p_status, p_error_code, p_data)
	RETURNING usage_event_id;
$$;

CREATE OR REPLACE FUNCTION get_usage_events_by_session_id_sp(p_session_id integer)
RETURNS SETOF usage_events
LANGUAGE sql STABLE AS $$
	SELECT * FROM usage_events WHERE session_id = p_session_id ORDER BY usage_event_id;
$$;

CREATE OR REPLACE FUNCTION update_usage_event_sp(
	p_usage_event_id integer, p_session_id integer, p_message_id integer, p_provider text, p_transport text,
	p_model_name text, p_reasoning_level text, p_provider_client_type text, p_credential_source text,
	p_credential_profile_id text, p_credential_display_name text, p_credential_fingerprint text,
	p_effective_base_url text, p_provider_request_id text, p_provider_response_id text, p_input_tokens integer,
	p_output_tokens integer, p_reasoning_tokens integer, p_cached_tokens integer, p_total_tokens integer,
	p_latency_ms integer, p_usage_operation text, p_operation_reference_id text, p_compaction_epoch integer,
	p_compaction_epoch_key text, p_provider_limit_snapshot_usage_event_id integer, p_status text, p_error_code text, p_data text)
RETURNS void LANGUAGE sql AS $$
	UPDATE usage_events SET session_id = p_session_id, message_id = p_message_id, provider = p_provider,
		transport = p_transport, model_name = p_model_name, reasoning_level = p_reasoning_level,
		provider_client_type = p_provider_client_type, credential_source = p_credential_source,
		credential_profile_id = p_credential_profile_id, credential_display_name = p_credential_display_name,
		credential_fingerprint = p_credential_fingerprint, effective_base_url = p_effective_base_url,
		provider_request_id = p_provider_request_id, provider_response_id = p_provider_response_id,
		input_tokens = p_input_tokens, output_tokens = p_output_tokens, reasoning_tokens = p_reasoning_tokens,
		cached_tokens = p_cached_tokens, total_tokens = p_total_tokens, latency_ms = p_latency_ms,
		usage_operation = p_usage_operation, operation_reference_id = p_operation_reference_id,
		compaction_epoch = p_compaction_epoch, compaction_epoch_key = p_compaction_epoch_key,
		provider_limit_snapshot_usage_event_id = p_provider_limit_snapshot_usage_event_id, status = p_status,
		error_code = p_error_code, data = p_data, last_updated = now()
	WHERE usage_event_id = p_usage_event_id;
$$;

CREATE OR REPLACE FUNCTION insert_completion_usage_event_sp(
	p_usage_event_key uuid,
	p_session_id integer,
	p_provider text,
	p_transport text,
	p_model_name text,
	p_reasoning_level text,
	p_provider_client_type text,
	p_credential_source text,
	p_credential_profile_id text,
	p_credential_display_name text,
	p_credential_fingerprint text,
	p_effective_base_url text,
	p_provider_request_id text,
	p_provider_response_id text,
	p_input_tokens integer,
	p_output_tokens integer,
	p_reasoning_tokens integer,
	p_cached_tokens integer,
	p_total_tokens integer,
	p_latency_ms integer,
	p_operation_reference_id text,
	p_compaction_epoch integer,
	p_compaction_epoch_key text,
	p_provider_limit_snapshot_usage_event_id integer,
	p_data text)
RETURNS TABLE ("UsageEventID" integer)
LANGUAGE plpgsql AS $$
DECLARE
	existing usage_events%ROWTYPE;
BEGIN
	IF p_usage_event_key IS NULL THEN RAISE EXCEPTION 'UsageEventKey is required.'; END IF;
	IF COALESCE(btrim(p_operation_reference_id), '') = '' THEN RAISE EXCEPTION 'OperationReferenceID is required.'; END IF;
	IF p_input_tokens < 0 OR p_output_tokens < 0 OR p_reasoning_tokens < 0 OR p_cached_tokens < 0 OR p_total_tokens < 0 OR p_latency_ms < 0 THEN
		RAISE EXCEPTION 'Completion usage counters cannot be negative.';
	END IF;

	INSERT INTO usage_events(usage_event_key, session_id, message_id, provider, transport, model_name, reasoning_level,
		provider_client_type, credential_source, credential_profile_id, credential_display_name, credential_fingerprint,
		effective_base_url, provider_request_id, provider_response_id, input_tokens, output_tokens, reasoning_tokens,
		cached_tokens, total_tokens, latency_ms, usage_operation, operation_reference_id, compaction_epoch,
		compaction_epoch_key, provider_limit_snapshot_usage_event_id, status, error_code, data, date_created, last_updated)
	VALUES(p_usage_event_key, p_session_id, NULL, p_provider, p_transport, p_model_name, p_reasoning_level,
		p_provider_client_type, p_credential_source, p_credential_profile_id, p_credential_display_name, p_credential_fingerprint,
		p_effective_base_url, p_provider_request_id, p_provider_response_id, p_input_tokens, p_output_tokens, p_reasoning_tokens,
		p_cached_tokens, p_total_tokens, p_latency_ms, 'completion', p_operation_reference_id, p_compaction_epoch,
		p_compaction_epoch_key, p_provider_limit_snapshot_usage_event_id, 'succeeded', NULL, p_data, now(), now())
	ON CONFLICT (session_id, usage_event_key) WHERE usage_event_key IS NOT NULL DO NOTHING;

	SELECT * INTO existing FROM usage_events WHERE session_id = p_session_id AND usage_event_key = p_usage_event_key;
	IF FOUND THEN
		IF existing.usage_operation <> 'completion' OR existing.status <> 'succeeded'
			OR existing.operation_reference_id IS DISTINCT FROM p_operation_reference_id
			OR existing.provider IS DISTINCT FROM p_provider OR existing.transport IS DISTINCT FROM p_transport
			OR existing.model_name IS DISTINCT FROM p_model_name OR existing.input_tokens <> p_input_tokens
			OR existing.output_tokens <> p_output_tokens OR existing.reasoning_tokens <> p_reasoning_tokens
			OR existing.cached_tokens <> p_cached_tokens OR existing.total_tokens <> p_total_tokens THEN
			RAISE EXCEPTION 'UsageEventKey already exists with different completion usage.';
		END IF;
		RETURN QUERY SELECT existing.usage_event_id;
		RETURN;
	END IF;
	RAISE EXCEPTION 'Completion usage insert did not produce a row.';
END;
$$;

CREATE OR REPLACE FUNCTION get_completion_usage_ledger_snapshot_sp(p_session_id integer, p_turn_key text, p_current_compaction_epoch integer)
RETURNS TABLE (
	"TurnCompletionCount" bigint, "TurnInputTokens" bigint, "TurnOutputTokens" bigint, "TurnReasoningTokens" bigint, "TurnCachedTokens" bigint, "TurnTotalTokens" bigint,
	"LifetimeCompletionCount" bigint, "LifetimeInputTokens" bigint, "LifetimeOutputTokens" bigint, "LifetimeReasoningTokens" bigint, "LifetimeCachedTokens" bigint, "LifetimeTotalTokens" bigint,
	"CurrentEpochCompletionCount" bigint, "CurrentEpochInputTokens" bigint, "CurrentEpochOutputTokens" bigint, "CurrentEpochReasoningTokens" bigint, "CurrentEpochCachedTokens" bigint, "CurrentEpochTotalTokens" bigint)
LANGUAGE sql AS $$
	SELECT
		COUNT(*) FILTER (WHERE operation_reference_id = p_turn_key),
		COALESCE(SUM(input_tokens::bigint) FILTER (WHERE operation_reference_id = p_turn_key), 0),
		COALESCE(SUM(output_tokens::bigint) FILTER (WHERE operation_reference_id = p_turn_key), 0),
		COALESCE(SUM(reasoning_tokens::bigint) FILTER (WHERE operation_reference_id = p_turn_key), 0),
		COALESCE(SUM(cached_tokens::bigint) FILTER (WHERE operation_reference_id = p_turn_key), 0),
		COALESCE(SUM(total_tokens::bigint) FILTER (WHERE operation_reference_id = p_turn_key), 0),
		COUNT(*), COALESCE(SUM(input_tokens::bigint), 0), COALESCE(SUM(output_tokens::bigint), 0),
		COALESCE(SUM(reasoning_tokens::bigint), 0), COALESCE(SUM(cached_tokens::bigint), 0), COALESCE(SUM(total_tokens::bigint), 0),
		COUNT(*) FILTER (WHERE compaction_epoch = p_current_compaction_epoch),
		COALESCE(SUM(input_tokens::bigint) FILTER (WHERE compaction_epoch = p_current_compaction_epoch), 0),
		COALESCE(SUM(output_tokens::bigint) FILTER (WHERE compaction_epoch = p_current_compaction_epoch), 0),
		COALESCE(SUM(reasoning_tokens::bigint) FILTER (WHERE compaction_epoch = p_current_compaction_epoch), 0),
		COALESCE(SUM(cached_tokens::bigint) FILTER (WHERE compaction_epoch = p_current_compaction_epoch), 0),
		COALESCE(SUM(total_tokens::bigint) FILTER (WHERE compaction_epoch = p_current_compaction_epoch), 0)
	FROM usage_events
	WHERE session_id = p_session_id AND usage_operation = 'completion' AND status = 'succeeded';
$$;
