CREATE TABLE IF NOT EXISTS turns(
 turn_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,session_id integer NOT NULL,turn_key text NOT NULL,
 display_order_at_utc timestamp NOT NULL,first_message_id integer,user_message_id integer,assistant_message_id integer,last_error_message_id integer,terminal_message_id integer,
 CONSTRAINT uq_turns_session_key UNIQUE(session_id,turn_key),CONSTRAINT ck_turns_key CHECK(length(turn_key)>0));
ALTER TABLE messages ALTER COLUMN turn_id DROP NOT NULL;
CREATE INDEX IF NOT EXISTS ix_turns_page ON turns(session_id,display_order_at_utc DESC,first_message_id DESC);
CREATE INDEX IF NOT EXISTS ix_messages_turn_row ON messages(session_id,turn_row_id,date_created DESC,message_id DESC);
