DROP FUNCTION IF EXISTS messages_get_by_message_ids_sp(text);
DROP FUNCTION IF EXISTS get_messages_by_session_idsp_count_sp(integer,text);
DROP FUNCTION IF EXISTS get_messages_by_session_idsp_paging_sp(integer,text,text,boolean,integer,integer);
DROP FUNCTION IF EXISTS get_messages_since_by_session_idand_message_key_sp(integer,text,integer);
DROP FUNCTION IF EXISTS get_messages_before_by_session_idand_message_key_sp(integer,text,integer);
DROP FUNCTION IF EXISTS messages_get_by_session_idturn_key_sp(integer,text);
CREATE TABLE IF NOT EXISTS messages (
	message_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id integer NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
	sequence_number integer NOT NULL,
	role text NOT NULL,
	content text NOT NULL,
	tool_name text NULL,
	tool_arguments text NULL,
	call_id text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	data text NULL,
	is_compacted boolean NOT NULL DEFAULT false,
	compaction_epoch integer NULL,
	message_key text NOT NULL,
	turn_id text NOT NULL,
	compaction_epoch_key text NULL
);
DROP INDEX IF EXISTS ux_messages_message_key;
CREATE INDEX IF NOT EXISTS ix_messages_message_key ON messages(message_key);
CREATE INDEX IF NOT EXISTS ix_messages_session_id_message_id ON messages(session_id, message_id);
CREATE INDEX IF NOT EXISTS ix_messages_session_id_message_key ON messages(session_id, message_key);
CREATE INDEX IF NOT EXISTS ix_messages_session_id_sequence_number ON messages(session_id, sequence_number, message_id);
CREATE INDEX IF NOT EXISTS ix_messages_turn_id ON messages(turn_id);
CREATE INDEX IF NOT EXISTS ix_messages_compaction_epoch_key ON messages(compaction_epoch_key);

CREATE OR REPLACE FUNCTION get_message_rows()
RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text)
LANGUAGE sql AS $$
	SELECT message_id,session_id,sequence_number,role,content,tool_name,tool_arguments,call_id,date_created,last_updated,data,is_compacted,compaction_epoch,message_key,turn_id,compaction_epoch_key
	FROM messages;
$$;

CREATE OR REPLACE FUNCTION insert_message_sp(p_session_id integer,p_sequence_number integer,p_role text,p_content text,p_tool_name text,p_tool_arguments text,p_call_id text,p_data text,p_is_compacted boolean,p_compaction_epoch integer,p_message_key text,p_turn_id text,p_compaction_epoch_key text)
RETURNS TABLE ("MessageID" integer) LANGUAGE sql AS $$
	INSERT INTO messages(session_id,sequence_number,role,content,tool_name,tool_arguments,call_id,date_created,last_updated,data,is_compacted,compaction_epoch,message_key,turn_id,compaction_epoch_key)
	VALUES(p_session_id,p_sequence_number,p_role,p_content,p_tool_name,p_tool_arguments,p_call_id,now(),now(),p_data,p_is_compacted,p_compaction_epoch,p_message_key,p_turn_id,p_compaction_epoch_key)
	RETURNING message_id;
$$;

CREATE OR REPLACE FUNCTION update_message_sp(p_message_id integer,p_session_id integer,p_sequence_number integer,p_role text,p_content text,p_tool_name text,p_tool_arguments text,p_call_id text,p_data text,p_is_compacted boolean,p_compaction_epoch integer,p_message_key text,p_thread_key text,p_compaction_epoch_key text)
RETURNS void LANGUAGE sql AS $$
	UPDATE messages SET session_id=p_session_id,sequence_number=p_sequence_number,role=p_role,content=p_content,tool_name=p_tool_name,tool_arguments=p_tool_arguments,call_id=p_call_id,last_updated=now(),data=p_data,is_compacted=p_is_compacted,compaction_epoch=p_compaction_epoch,message_key=p_message_key,turn_id=p_thread_key,compaction_epoch_key=p_compaction_epoch_key
	WHERE message_id=p_message_id;
$$;
CREATE OR REPLACE FUNCTION remove_message_sp(p_message_id integer) RETURNS void LANGUAGE sql AS $$ DELETE FROM messages WHERE message_id=p_message_id; $$;
CREATE OR REPLACE FUNCTION copy_message_sp(p_message_id integer) RETURNS TABLE ("MessageID" integer) LANGUAGE sql AS $$
	INSERT INTO messages(session_id,sequence_number,role,content,tool_name,tool_arguments,call_id,date_created,last_updated,data,is_compacted,compaction_epoch,message_key,turn_id,compaction_epoch_key)
	SELECT session_id,sequence_number,role,content,tool_name,tool_arguments,call_id,now(),now(),data,is_compacted,compaction_epoch,message_key || '-copy-' || replace(clock_timestamp()::text, ' ', '-') || '-' || floor(random() * 1000000)::integer::text,turn_id,compaction_epoch_key FROM messages WHERE message_id=p_message_id
	RETURNING message_id;
$$;
CREATE OR REPLACE FUNCTION update_message_tool_arguments_sp(p_message_id integer,p_tool_arguments text) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET tool_arguments=p_tool_arguments,last_updated=now() WHERE message_id=p_message_id; $$;
CREATE OR REPLACE FUNCTION update_message_data_sp(p_message_id integer,p_data text) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET data=p_data,last_updated=now() WHERE message_id=p_message_id; $$;
CREATE OR REPLACE FUNCTION mark_message_as_compacted_sp(p_message_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET is_compacted=true,last_updated=now() WHERE message_id=p_message_id; $$;
CREATE OR REPLACE FUNCTION mark_message_as_not_compacted_sp(p_message_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE messages SET is_compacted=false,last_updated=now() WHERE message_id=p_message_id; $$;

CREATE OR REPLACE FUNCTION get_message_sp(p_message_id integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "MessageID"=p_message_id; $$;
CREATE OR REPLACE FUNCTION get_messages_sp() RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() ORDER BY "MessageID" ASC; $$;
CREATE OR REPLACE FUNCTION get_messages_by_session_id_sp(p_session_id integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "SessionID"=p_session_id ORDER BY "SequenceNumber" ASC,"MessageID" ASC; $$;
CREATE OR REPLACE FUNCTION get_messages_by_message_key_sp(p_message_key text) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "MessageKey"=p_message_key ORDER BY "MessageID" ASC; $$;
CREATE OR REPLACE FUNCTION get_message_by_message_key_sp(p_message_key text) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "MessageKey"=p_message_key ORDER BY "MessageID" ASC LIMIT 1; $$;
CREATE OR REPLACE FUNCTION get_messages_by_compaction_epoch_key_sp(p_compaction_epoch_key text) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "CompactionEpochKey"=p_compaction_epoch_key ORDER BY "MessageID" ASC; $$;
CREATE OR REPLACE FUNCTION get_messages_by_compaction_epoch_key_session_id_sp(p_compaction_epoch_key text,p_session_id integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "SessionID"=p_session_id AND ((p_compaction_epoch_key IS NULL AND "CompactionEpochKey" IS NULL) OR "CompactionEpochKey"=p_compaction_epoch_key) ORDER BY "MessageID" ASC; $$;
CREATE OR REPLACE FUNCTION get_messages_by_turn_id_sp(p_turn_id text) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "TurnID"=p_turn_id ORDER BY "SequenceNumber" ASC,"MessageID" ASC; $$;

CREATE OR REPLACE FUNCTION messages_get_by_message_search_sp(p_search text,p_max_rows integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "Role"='user' AND "Content" ILIKE '%'||COALESCE(p_search,'')||'%' ORDER BY "MessageID" DESC LIMIT p_max_rows; $$;
CREATE OR REPLACE FUNCTION messages_get_by_final_assistant_search_sp(p_search text,p_max_rows integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "Role"='assistant' AND "Content" ILIKE '%'||COALESCE(p_search,'')||'%' ORDER BY "MessageID" DESC LIMIT p_max_rows; $$;
CREATE OR REPLACE FUNCTION get_messages_since_by_session_idand_message_key_sp(p_session_id integer,p_message_key text,p_num_rows integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "SessionID"=p_session_id AND "MessageID" > (SELECT message_id FROM messages WHERE session_id=p_session_id AND message_key=p_message_key LIMIT 1) ORDER BY "MessageID" ASC LIMIT p_num_rows; $$;

CREATE OR REPLACE FUNCTION messages_get_turn_deltas_since_by_session_idand_message_key_sp(p_session_id integer,p_message_key text,p_num_rows integer) RETURNS TABLE ("MessageKey" text,"TurnID" text) LANGUAGE sql AS $$ SELECT message_key, COALESCE(turn_id, '') FROM messages WHERE session_id=p_session_id AND message_id > (SELECT message_id FROM messages WHERE session_id=p_session_id AND message_key=p_message_key LIMIT 1) ORDER BY message_id ASC LIMIT p_num_rows; $$;
CREATE OR REPLACE FUNCTION get_messages_before_by_session_idand_message_key_sp(p_session_id integer,p_message_key text,p_num_rows integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM (SELECT * FROM get_message_rows() WHERE "SessionID"=p_session_id AND "MessageID" < (SELECT message_id FROM messages WHERE session_id=p_session_id AND message_key=p_message_key LIMIT 1) ORDER BY "MessageID" DESC LIMIT p_num_rows) rows ORDER BY "MessageID" ASC; $$;
CREATE OR REPLACE FUNCTION get_all_epochs_by_session_id_sp(p_session_id integer) RETURNS TABLE ("CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT DISTINCT compaction_epoch_key FROM messages WHERE session_id=p_session_id AND compaction_epoch_key IS NOT NULL ORDER BY compaction_epoch_key; $$;
CREATE OR REPLACE FUNCTION messages_get_count_by_session_id_sp(p_session_id integer) RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$ SELECT COUNT(*)::integer FROM messages WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION messages_get_by_session_id_sp(p_session_id integer,p_skip_rows integer,p_num_rows integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "SessionID"=p_session_id ORDER BY "MessageID" DESC OFFSET p_skip_rows LIMIT p_num_rows; $$;
CREATE OR REPLACE FUNCTION messages_get_by_session_idturn_key_sp(p_session_id integer,p_turn_key text) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "SessionID"=p_session_id AND "TurnID"=p_turn_key ORDER BY "SequenceNumber" ASC,"MessageID" ASC; $$;
CREATE OR REPLACE FUNCTION messages_get_by_message_ids_sp(p_message_i_ds_csv text) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT r.* FROM get_message_rows() r JOIN regexp_split_to_table(COALESCE(p_message_i_ds_csv,''), ',') ids(id_text) ON r."MessageID"=NULLIF(trim(ids.id_text),'')::integer ORDER BY r."MessageID" ASC; $$;
CREATE OR REPLACE FUNCTION messages_get_latest_message_key_by_session_id_sp(p_session_id integer) RETURNS TABLE ("MessageKey" text) LANGUAGE sql AS $$ SELECT message_key FROM messages WHERE session_id=p_session_id ORDER BY message_id DESC LIMIT 1; $$;

CREATE OR REPLACE FUNCTION get_messages_by_session_idsp_count_sp(p_session_id integer,p_search text) RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$ SELECT COUNT(*)::integer FROM get_message_rows() WHERE "SessionID"=p_session_id AND ("MessageKey" ILIKE '%'||COALESCE(p_search,'')||'%' OR "Role" ILIKE '%'||COALESCE(p_search,'')||'%' OR "Content" ILIKE '%'||COALESCE(p_search,'')||'%'); $$;
CREATE OR REPLACE FUNCTION get_messages_sp_count_sp(p_search text) RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$ SELECT COUNT(*)::integer FROM get_message_rows() WHERE "MessageKey" ILIKE '%'||COALESCE(p_search,'')||'%' OR "Role" ILIKE '%'||COALESCE(p_search,'')||'%' OR "Content" ILIKE '%'||COALESCE(p_search,'')||'%'; $$;
CREATE OR REPLACE FUNCTION get_messages_by_session_idsp_paging_sp(p_session_id integer,p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "SessionID"=p_session_id AND ("MessageKey" ILIKE '%'||COALESCE(p_search,'')||'%' OR "Role" ILIKE '%'||COALESCE(p_search,'')||'%' OR "Content" ILIKE '%'||COALESCE(p_search,'')||'%') ORDER BY CASE WHEN p_sort_column='MessageID' AND p_sort_ascending THEN "MessageID" END ASC, CASE WHEN p_sort_column='MessageID' AND NOT p_sort_ascending THEN "MessageID" END DESC, "MessageID" ASC OFFSET p_skip_rows LIMIT p_num_rows; $$;
CREATE OR REPLACE FUNCTION get_messages_sp_paging_sp(p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_message_rows() WHERE "MessageKey" ILIKE '%'||COALESCE(p_search,'')||'%' OR "Role" ILIKE '%'||COALESCE(p_search,'')||'%' OR "Content" ILIKE '%'||COALESCE(p_search,'')||'%' ORDER BY CASE WHEN p_sort_column='MessageID' AND p_sort_ascending THEN "MessageID" END ASC, CASE WHEN p_sort_column='MessageID' AND NOT p_sort_ascending THEN "MessageID" END DESC, "MessageID" ASC OFFSET p_skip_rows LIMIT p_num_rows; $$;
-- Compatibility aliases for the generated repository name mapper, which preserves some acronym boundaries such as IDAnd and IDTurn.
CREATE OR REPLACE FUNCTION get_messages_by_compaction_epoch_key_session_idsp(p_compaction_epoch_key text,p_session_id integer) RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text) LANGUAGE sql AS $$ SELECT * FROM get_messages_by_compaction_epoch_key_session_id_sp(p_compaction_epoch_key,p_session_id); $$;


SELECT record_schema_migration('006_messages_repository_routines');

DROP FUNCTION IF EXISTS messages_get_by_session_iddate_range_sp(integer,timestamp,timestamp,integer);
DROP FUNCTION IF EXISTS "Messages_GetBySessionIDDateRangeSp"(integer,timestamp,timestamp,integer);
DROP FUNCTION IF EXISTS update_messages_compaction_epoch_by_message_keys_json_sp(integer,text,integer,text);
DROP FUNCTION IF EXISTS "UpdateMessagesCompactionEpochByMessageKeysJsonSp"(integer,text,integer,text);
DROP FUNCTION IF EXISTS update_message_date_created_sp(integer,timestamp);
DROP FUNCTION IF EXISTS "UpdateMessageDateCreatedSp"(integer,timestamp);

CREATE OR REPLACE FUNCTION messages_get_by_session_iddate_range_sp(p_session_id integer,p_start_utc timestamp,p_end_utc timestamp,p_num_rows integer)
RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text)
LANGUAGE sql AS $$
	SELECT *
	FROM get_message_rows()
	WHERE "SessionID" = p_session_id
		AND (p_start_utc IS NULL OR "DateCreated" >= p_start_utc)
		AND (p_end_utc IS NULL OR "DateCreated" <= p_end_utc)
	ORDER BY "MessageID" ASC
	LIMIT p_num_rows;
$$;

CREATE OR REPLACE FUNCTION "Messages_GetBySessionIDDateRangeSp"(p_session_id integer,p_start_utc timestamp,p_end_utc timestamp,p_num_rows integer)
RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text)
LANGUAGE sql AS $$
SELECT * FROM messages_get_by_session_iddate_range_sp(p_session_id,p_start_utc,p_end_utc,p_num_rows);
$$;

CREATE OR REPLACE FUNCTION update_messages_compaction_epoch_by_message_keys_json_sp(p_session_id integer,p_message_keys_json text,p_compaction_epoch integer,p_compaction_epoch_key text)
RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text)
LANGUAGE sql AS $$
	WITH keys AS (
		SELECT DISTINCT trim(value) AS message_key
		FROM json_array_elements_text(p_message_keys_json::json) value
		WHERE length(trim(value)) > 0
	), updated AS (
		UPDATE messages m
		SET compaction_epoch = p_compaction_epoch,
			compaction_epoch_key = p_compaction_epoch_key,
			last_updated = now()
		FROM keys k
		WHERE m.session_id = p_session_id
			AND m.message_key = k.message_key
		RETURNING m.message_id
	)
	SELECT r.*
	FROM get_message_rows() r
	INNER JOIN updated u ON u.message_id = r."MessageID"
	ORDER BY r."SequenceNumber" ASC, r."MessageID" ASC;
$$;

CREATE OR REPLACE FUNCTION "UpdateMessagesCompactionEpochByMessageKeysJsonSp"(p_session_id integer,p_message_keys_json text,p_compaction_epoch integer,p_compaction_epoch_key text)
RETURNS TABLE ("MessageID" integer,"SessionID" integer,"SequenceNumber" integer,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"IsCompacted" boolean,"CompactionEpoch" integer,"MessageKey" text,"TurnID" text,"CompactionEpochKey" text)
LANGUAGE sql AS $$
SELECT * FROM update_messages_compaction_epoch_by_message_keys_json_sp(p_session_id,p_message_keys_json,p_compaction_epoch,p_compaction_epoch_key);
$$;

CREATE OR REPLACE FUNCTION update_message_compaction_epoch_atomic_sp(p_session_id integer,p_message_key text,p_compaction_epoch integer,p_compaction_epoch_key text)
RETURNS TABLE ("UpdatedRows" integer)
LANGUAGE plpgsql AS $$
DECLARE
	v_message_id integer;
BEGIN
	SELECT message_id INTO v_message_id
	FROM messages
	WHERE session_id = p_session_id
		AND message_key = p_message_key
	ORDER BY message_id ASC
	LIMIT 1;

	IF v_message_id IS NULL THEN
		RETURN QUERY SELECT 0;
		RETURN;
	END IF;

	UPDATE messages
	SET compaction_epoch = p_compaction_epoch,
		compaction_epoch_key = p_compaction_epoch_key,
		last_updated = now()
	WHERE message_id = v_message_id;

	RETURN QUERY SELECT 1;
END;
$$;

CREATE OR REPLACE FUNCTION "UpdateMessageCompactionEpochAtomicSp"(p_session_id integer,p_message_key text,p_compaction_epoch integer,p_compaction_epoch_key text)
RETURNS TABLE ("UpdatedRows" integer)
LANGUAGE sql AS $$
SELECT * FROM update_message_compaction_epoch_atomic_sp(p_session_id,p_message_key,p_compaction_epoch,p_compaction_epoch_key);
$$;

CREATE OR REPLACE FUNCTION update_message_date_created_sp(p_message_id integer,p_date_created timestamp)
RETURNS void LANGUAGE sql AS $$
	UPDATE messages SET date_created = p_date_created WHERE message_id = p_message_id;
$$;

CREATE OR REPLACE FUNCTION "UpdateMessageDateCreatedSp"(p_message_id integer,p_date_created timestamp)
RETURNS void LANGUAGE sql AS $$
SELECT update_message_date_created_sp(p_message_id,p_date_created);
$$;
