CREATE TABLE IF NOT EXISTS session_artifacts (
	session_artifact_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id integer NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
	source_message_id integer NULL REFERENCES messages(message_id) ON DELETE SET NULL,
	artifact_type text NOT NULL,
	artifact_name text NOT NULL,
	file_path text NULL,
	summary text NULL,
	content_data text NULL,
	mime_type text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	data text NULL
);
CREATE INDEX IF NOT EXISTS ix_session_artifacts_session_id ON session_artifacts(session_id, session_artifact_id);
CREATE INDEX IF NOT EXISTS ix_session_artifacts_source_message_id ON session_artifacts(source_message_id);
CREATE INDEX IF NOT EXISTS ix_session_artifacts_artifact_type ON session_artifacts(artifact_type);
CREATE INDEX IF NOT EXISTS ix_session_artifacts_artifact_name ON session_artifacts(artifact_name);
CREATE INDEX IF NOT EXISTS ix_session_artifacts_file_path ON session_artifacts(file_path);

CREATE OR REPLACE FUNCTION get_session_artifact_rows()
RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text)
LANGUAGE sql AS $$
	SELECT session_artifact_id,session_id,source_message_id,artifact_type,artifact_name,file_path,summary,content_data,mime_type,date_created,last_updated,data
	FROM session_artifacts;
$$;

CREATE OR REPLACE FUNCTION insert_session_artifact_sp(p_session_id integer,p_source_message_id integer,p_artifact_type text,p_artifact_name text,p_file_path text,p_summary text,p_content_data text,p_mime_type text,p_data text)
RETURNS TABLE ("SessionArtifactID" integer) LANGUAGE sql AS $$
	INSERT INTO session_artifacts(session_id,source_message_id,artifact_type,artifact_name,file_path,summary,content_data,mime_type,date_created,last_updated,data)
	VALUES(p_session_id,p_source_message_id,p_artifact_type,p_artifact_name,p_file_path,p_summary,p_content_data,p_mime_type,now(),now(),p_data)
	RETURNING session_artifact_id;
$$;

CREATE OR REPLACE FUNCTION update_session_artifact_sp(p_session_artifact_id integer,p_session_id integer,p_source_message_id integer,p_artifact_type text,p_artifact_name text,p_file_path text,p_summary text,p_content_data text,p_mime_type text,p_data text)
RETURNS void LANGUAGE sql AS $$
	UPDATE session_artifacts SET session_id=p_session_id,source_message_id=p_source_message_id,artifact_type=p_artifact_type,artifact_name=p_artifact_name,file_path=p_file_path,summary=p_summary,content_data=p_content_data,mime_type=p_mime_type,last_updated=now(),data=p_data
	WHERE session_artifact_id=p_session_artifact_id;
$$;
CREATE OR REPLACE FUNCTION remove_session_artifact_sp(p_session_artifact_id integer) RETURNS void LANGUAGE sql AS $$ DELETE FROM session_artifacts WHERE session_artifact_id=p_session_artifact_id; $$;
CREATE OR REPLACE FUNCTION copy_session_artifact_sp(p_session_artifact_id integer) RETURNS TABLE ("SessionArtifactID" integer) LANGUAGE sql AS $$
	INSERT INTO session_artifacts(session_id,source_message_id,artifact_type,artifact_name,file_path,summary,content_data,mime_type,date_created,last_updated,data)
	SELECT session_id,source_message_id,artifact_type,artifact_name,file_path,summary,content_data,mime_type,now(),now(),data FROM session_artifacts WHERE session_artifact_id=p_session_artifact_id
	RETURNING session_artifact_id;
$$;
CREATE OR REPLACE FUNCTION update_session_artifact_content_data_sp(p_session_artifact_id integer,p_content_data text) RETURNS void LANGUAGE sql AS $$ UPDATE session_artifacts SET content_data=p_content_data,last_updated=now() WHERE session_artifact_id=p_session_artifact_id; $$;
CREATE OR REPLACE FUNCTION update_session_artifact_data_sp(p_session_artifact_id integer,p_data text) RETURNS void LANGUAGE sql AS $$ UPDATE session_artifacts SET data=p_data,last_updated=now() WHERE session_artifact_id=p_session_artifact_id; $$;

CREATE OR REPLACE FUNCTION get_session_artifact_sp(p_session_artifact_id integer) RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_artifact_rows() WHERE "SessionArtifactID"=p_session_artifact_id; $$;
CREATE OR REPLACE FUNCTION get_session_artifacts_sp() RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_artifact_rows() ORDER BY "SessionArtifactID" ASC; $$;
CREATE OR REPLACE FUNCTION get_session_artifacts_by_session_id_sp(p_session_id integer) RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_artifact_rows() WHERE "SessionID"=p_session_id ORDER BY "SessionArtifactID" ASC; $$;
CREATE OR REPLACE FUNCTION get_session_artifacts_by_source_message_id_sp(p_source_message_id integer) RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_artifact_rows() WHERE "SourceMessageID"=p_source_message_id ORDER BY "SessionArtifactID" ASC; $$;
CREATE OR REPLACE FUNCTION get_session_artifacts_by_artifact_type_sp(p_artifact_type text) RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_artifact_rows() WHERE "ArtifactType"=p_artifact_type ORDER BY "SessionArtifactID" ASC; $$;
CREATE OR REPLACE FUNCTION get_session_artifact_by_session_idand_artifact_name_sp(p_session_id integer,p_artifact_name text) RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_artifact_rows() WHERE "SessionID"=p_session_id AND "ArtifactName"=p_artifact_name ORDER BY "SessionArtifactID" ASC LIMIT 1; $$;
CREATE OR REPLACE FUNCTION get_session_artifact_by_file_path_sp(p_file_path text) RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$ SELECT * FROM get_session_artifact_rows() WHERE "FilePath"=p_file_path ORDER BY "SessionArtifactID" ASC LIMIT 1; $$;

CREATE OR REPLACE FUNCTION session_artifact_search_matches(p_session_artifact_id integer,p_artifact_type text,p_artifact_name text,p_file_path text,p_summary text,p_mime_type text,p_search text)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
	SELECT COALESCE(p_search,'') = ''
		OR p_session_artifact_id::text ILIKE '%' || p_search || '%'
		OR p_artifact_type ILIKE '%' || p_search || '%'
		OR p_artifact_name ILIKE '%' || p_search || '%'
		OR COALESCE(p_file_path,'') ILIKE '%' || p_search || '%'
		OR COALESCE(p_summary,'') ILIKE '%' || p_search || '%'
		OR COALESCE(p_mime_type,'') ILIKE '%' || p_search || '%';
$$;
CREATE OR REPLACE FUNCTION get_session_artifacts_sp_count_sp(p_search text) RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$ SELECT COUNT(*)::integer FROM session_artifacts WHERE session_artifact_search_matches(session_artifact_id,artifact_type,artifact_name,file_path,summary,mime_type,p_search); $$;
CREATE OR REPLACE FUNCTION get_session_artifacts_sp_paging_sp(p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer) RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$
	SELECT * FROM get_session_artifact_rows()
	WHERE session_artifact_search_matches("SessionArtifactID","ArtifactType","ArtifactName","FilePath","Summary","MimeType",p_search)
	ORDER BY
		CASE WHEN p_sort_column='SessionArtifactID' AND p_sort_ascending THEN "SessionArtifactID" END ASC,
		CASE WHEN p_sort_column='SessionArtifactID' AND NOT p_sort_ascending THEN "SessionArtifactID" END DESC,
		CASE WHEN p_sort_column='ArtifactName' AND p_sort_ascending THEN "ArtifactName" END ASC,
		CASE WHEN p_sort_column='ArtifactName' AND NOT p_sort_ascending THEN "ArtifactName" END DESC,
		CASE WHEN p_sort_column='ArtifactType' AND p_sort_ascending THEN "ArtifactType" END ASC,
		CASE WHEN p_sort_column='ArtifactType' AND NOT p_sort_ascending THEN "ArtifactType" END DESC,
		"SessionArtifactID" ASC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;
CREATE OR REPLACE FUNCTION get_session_artifacts_by_session_idsp_count_sp(p_session_id integer,p_search text) RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$ SELECT COUNT(*)::integer FROM session_artifacts WHERE session_id=p_session_id AND session_artifact_search_matches(session_artifact_id,artifact_type,artifact_name,file_path,summary,mime_type,p_search); $$;
CREATE OR REPLACE FUNCTION get_session_artifacts_by_session_idsp_paging_sp(p_session_id integer,p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer) RETURNS TABLE ("SessionArtifactID" integer,"SessionID" integer,"SourceMessageID" integer,"ArtifactType" text,"ArtifactName" text,"FilePath" text,"Summary" text,"ContentData" text,"MimeType" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text) LANGUAGE sql AS $$
	SELECT * FROM get_session_artifact_rows()
	WHERE "SessionID"=p_session_id AND session_artifact_search_matches("SessionArtifactID","ArtifactType","ArtifactName","FilePath","Summary","MimeType",p_search)
	ORDER BY
		CASE WHEN p_sort_column='SessionArtifactID' AND p_sort_ascending THEN "SessionArtifactID" END ASC,
		CASE WHEN p_sort_column='SessionArtifactID' AND NOT p_sort_ascending THEN "SessionArtifactID" END DESC,
		CASE WHEN p_sort_column='ArtifactName' AND p_sort_ascending THEN "ArtifactName" END ASC,
		CASE WHEN p_sort_column='ArtifactName' AND NOT p_sort_ascending THEN "ArtifactName" END DESC,
		CASE WHEN p_sort_column='ArtifactType' AND p_sort_ascending THEN "ArtifactType" END ASC,
		CASE WHEN p_sort_column='ArtifactType' AND NOT p_sort_ascending THEN "ArtifactType" END DESC,
		"SessionArtifactID" ASC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;

SELECT record_schema_migration('007_session_artifacts_repository_routines');
