CREATE TABLE IF NOT EXISTS page_layouts (
	page_layout_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	url varchar(255) NOT NULL,
	handler varchar(255) NOT NULL,
	is_enabled boolean NOT NULL DEFAULT true,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	page_title varchar(255) NULL,
	site_id integer NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_page_layouts_url ON page_layouts (url);

CREATE OR REPLACE FUNCTION insert_page_layout_sp(p_url varchar(255), p_handler varchar(255), p_is_enabled boolean, p_page_title varchar(255), p_site_id integer)
RETURNS TABLE ("PageLayoutID" integer) LANGUAGE sql AS $$
	INSERT INTO page_layouts (url, handler, is_enabled, date_created, last_updated, page_title, site_id)
	VALUES (p_url, p_handler, p_is_enabled, now(), now(), p_page_title, p_site_id)
	RETURNING page_layout_id;
$$;

CREATE OR REPLACE FUNCTION update_page_layout_sp(p_page_layout_id integer, p_url varchar(255), p_handler varchar(255), p_is_enabled boolean, p_page_title varchar(255), p_site_id integer)
RETURNS void LANGUAGE sql AS $$
	UPDATE page_layouts SET url=p_url, handler=p_handler, is_enabled=p_is_enabled, last_updated=now(), page_title=p_page_title, site_id=p_site_id
	WHERE page_layout_id=p_page_layout_id;
$$;

CREATE OR REPLACE FUNCTION remove_page_layout_sp(p_page_layout_id integer)
RETURNS void LANGUAGE sql AS $$ DELETE FROM page_layouts WHERE page_layout_id=p_page_layout_id; $$;

CREATE OR REPLACE FUNCTION copy_page_layout_sp(p_page_layout_id integer)
RETURNS TABLE ("PageLayoutID" integer) LANGUAGE sql AS $$
	INSERT INTO page_layouts (url, handler, is_enabled, date_created, last_updated, page_title, site_id)
	SELECT url || '-copy-' || floor(extract(epoch from clock_timestamp()) * 1000000)::bigint::text, handler, is_enabled, now(), now(), page_title, site_id
	FROM page_layouts WHERE page_layout_id=p_page_layout_id
	RETURNING page_layout_id;
$$;

CREATE OR REPLACE FUNCTION get_page_layout_sp(p_page_layout_id integer)
RETURNS TABLE ("PageLayoutID" integer, "Url" varchar(255), "Handler" varchar(255), "IsEnabled" boolean, "DateCreated" timestamp, "LastUpdated" timestamp, "PageTitle" varchar(255), "SiteID" integer)
LANGUAGE sql AS $$
	SELECT page_layout_id, url, handler, is_enabled, date_created, last_updated, page_title, site_id FROM page_layouts WHERE page_layout_id=p_page_layout_id;
$$;

CREATE OR REPLACE FUNCTION get_page_layouts_sp()
RETURNS TABLE ("PageLayoutID" integer, "Url" varchar(255), "Handler" varchar(255), "IsEnabled" boolean, "DateCreated" timestamp, "LastUpdated" timestamp, "PageTitle" varchar(255), "SiteID" integer)
LANGUAGE sql AS $$
	SELECT page_layout_id, url, handler, is_enabled, date_created, last_updated, page_title, site_id FROM page_layouts;
$$;

CREATE OR REPLACE FUNCTION get_page_layout_by_url_sp(p_url varchar(255))
RETURNS TABLE ("PageLayoutID" integer, "Url" varchar(255), "Handler" varchar(255), "IsEnabled" boolean, "DateCreated" timestamp, "LastUpdated" timestamp, "PageTitle" varchar(255), "SiteID" integer)
LANGUAGE sql AS $$
	SELECT page_layout_id, url, handler, is_enabled, date_created, last_updated, page_title, site_id FROM page_layouts WHERE url=p_url;
$$;

CREATE OR REPLACE FUNCTION get_page_layouts_sp_count_sp(p_search varchar(255))
RETURNS integer LANGUAGE sql AS $$
	SELECT COUNT(*)::integer
	FROM page_layouts
	WHERE page_layout_id::varchar(50) LIKE '%'||COALESCE(p_search,'')||'%'
		OR url LIKE '%'||COALESCE(p_search,'')||'%'
		OR handler LIKE '%'||COALESCE(p_search,'')||'%'
		OR page_title LIKE '%'||COALESCE(p_search,'')||'%'
		OR site_id::varchar(50) LIKE '%'||COALESCE(p_search,'')||'%';
$$;

CREATE OR REPLACE FUNCTION get_page_layouts_sp_paging_sp(p_search varchar(255), p_sort_column varchar(255), p_sort_ascending boolean, p_skip_rows integer, p_num_rows integer)
RETURNS TABLE ("PageLayoutID" integer, "Url" varchar(255), "Handler" varchar(255), "IsEnabled" boolean, "DateCreated" timestamp, "LastUpdated" timestamp, "PageTitle" varchar(255), "SiteID" integer)
LANGUAGE sql AS $$
	SELECT page_layout_id, url, handler, is_enabled, date_created, last_updated, page_title, site_id
	FROM page_layouts
	WHERE page_layout_id::varchar(50) LIKE '%'||COALESCE(p_search,'')||'%'
		OR url LIKE '%'||COALESCE(p_search,'')||'%'
		OR handler LIKE '%'||COALESCE(p_search,'')||'%'
		OR page_title LIKE '%'||COALESCE(p_search,'')||'%'
		OR site_id::varchar(50) LIKE '%'||COALESCE(p_search,'')||'%'
	ORDER BY
		CASE WHEN p_sort_column='PageLayoutID' AND p_sort_ascending THEN page_layout_id END ASC,
		CASE WHEN p_sort_column='PageLayoutID' AND NOT p_sort_ascending THEN page_layout_id END DESC,
		CASE WHEN p_sort_column='Url' AND p_sort_ascending THEN url END ASC,
		CASE WHEN p_sort_column='Url' AND NOT p_sort_ascending THEN url END DESC,
		CASE WHEN p_sort_column='Handler' AND p_sort_ascending THEN handler END ASC,
		CASE WHEN p_sort_column='Handler' AND NOT p_sort_ascending THEN handler END DESC,
		CASE WHEN p_sort_column='IsEnabled' AND p_sort_ascending THEN is_enabled END ASC,
		CASE WHEN p_sort_column='IsEnabled' AND NOT p_sort_ascending THEN is_enabled END DESC,
		CASE WHEN p_sort_column='DateCreated' AND p_sort_ascending THEN date_created END ASC,
		CASE WHEN p_sort_column='DateCreated' AND NOT p_sort_ascending THEN date_created END DESC,
		CASE WHEN p_sort_column='LastUpdated' AND p_sort_ascending THEN last_updated END ASC,
		CASE WHEN p_sort_column='LastUpdated' AND NOT p_sort_ascending THEN last_updated END DESC,
		CASE WHEN p_sort_column='PageTitle' AND p_sort_ascending THEN page_title END ASC,
		CASE WHEN p_sort_column='PageTitle' AND NOT p_sort_ascending THEN page_title END DESC,
		CASE WHEN p_sort_column='SiteID' AND p_sort_ascending THEN site_id END ASC,
		CASE WHEN p_sort_column='SiteID' AND NOT p_sort_ascending THEN site_id END DESC,
		page_layout_id ASC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;

CREATE OR REPLACE FUNCTION mark_page_layout_as_enabled_sp(p_page_layout_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE page_layouts SET is_enabled=true, last_updated=now() WHERE page_layout_id=p_page_layout_id; $$;
CREATE OR REPLACE FUNCTION mark_page_layout_as_not_enabled_sp(p_page_layout_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE page_layouts SET is_enabled=false, last_updated=now() WHERE page_layout_id=p_page_layout_id; $$;

SELECT record_schema_migration('008_page_layouts_repository_routines');