IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE Specific_Name = 'StoredProcedureHasParameterSp')
BEGIN
	DROP PROCEDURE StoredProcedureHasParameterSp
END
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[StoredProcedureHasParameterSp]
	@StoredProcedureName [nvarchar](255),
	@ParameterName [nvarchar](255)
AS

	SET NOCOUNT ON

	SELECT CASE WHEN EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.PARAMETERS
		WHERE SPECIFIC_NAME = @StoredProcedureName
			AND PARAMETER_NAME = @ParameterName
	) THEN 1 ELSE 0 END AS HasParameter

GO
