DROP FUNCTION IF EXISTS insert_feature_sp(varchar,varchar,boolean,varchar,varchar,text,text);
DROP FUNCTION IF EXISTS copy_feature_sp(integer);
CREATE TABLE IF NOT EXISTS features (
	feature_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	feature_name varchar(255) NOT NULL,
	version varchar(255) NULL,
	is_enabled boolean NOT NULL DEFAULT true,
	settings_assembly varchar(255) NULL,
	settings_class varchar(255) NOT NULL,
	settings text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	data text NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_features_feature_name ON features (feature_name);

CREATE OR REPLACE FUNCTION insert_feature_sp(p_feature_name varchar(255), p_version varchar(255), p_is_enabled boolean, p_settings_assembly varchar(255), p_settings_class varchar(255), p_settings text, p_data text)
RETURNS TABLE ("FeatureID" integer) LANGUAGE sql AS $$
	INSERT INTO features (feature_name, version, is_enabled, settings_assembly, settings_class, settings, date_created, last_updated, data)
	VALUES (p_feature_name, p_version, p_is_enabled, p_settings_assembly, p_settings_class, p_settings, now(), now(), p_data)
	RETURNING feature_id;
$$;

CREATE OR REPLACE FUNCTION update_feature_sp(p_feature_id integer, p_feature_name varchar(255), p_version varchar(255), p_is_enabled boolean, p_settings_assembly varchar(255), p_settings_class varchar(255), p_settings text, p_data text)
RETURNS void LANGUAGE sql AS $$
	UPDATE features SET feature_name=p_feature_name, version=p_version, is_enabled=p_is_enabled, settings_assembly=p_settings_assembly, settings_class=p_settings_class, settings=p_settings, last_updated=now(), data=p_data
	WHERE feature_id=p_feature_id;
$$;

CREATE OR REPLACE FUNCTION remove_feature_sp(p_feature_id integer)
RETURNS void LANGUAGE sql AS $$ DELETE FROM features WHERE feature_id=p_feature_id; $$;

CREATE OR REPLACE FUNCTION copy_feature_sp(p_feature_id integer)
RETURNS TABLE ("FeatureID" integer) LANGUAGE sql AS $$
	INSERT INTO features (feature_name, version, is_enabled, settings_assembly, settings_class, settings, date_created, last_updated, data)
	SELECT feature_name || ' - Copy', version, is_enabled, settings_assembly, settings_class, settings, now(), now(), data
	FROM features WHERE feature_id=p_feature_id
	RETURNING feature_id;
$$;

CREATE OR REPLACE FUNCTION get_feature_sp(p_feature_id integer)
RETURNS TABLE ("FeatureID" integer, "FeatureName" varchar(255), "Version" varchar(255), "IsEnabled" boolean, "SettingsAssembly" varchar(255), "SettingsClass" varchar(255), "Settings" text, "DateCreated" timestamp, "LastUpdated" timestamp, "Data" text)
LANGUAGE sql AS $$
	SELECT feature_id, feature_name, version, is_enabled, settings_assembly, settings_class, settings, date_created, last_updated, data FROM features WHERE feature_id=p_feature_id;
$$;

CREATE OR REPLACE FUNCTION get_features_sp()
RETURNS TABLE ("FeatureID" integer, "FeatureName" varchar(255), "Version" varchar(255), "IsEnabled" boolean, "SettingsAssembly" varchar(255), "SettingsClass" varchar(255), "Settings" text, "DateCreated" timestamp, "LastUpdated" timestamp, "Data" text)
LANGUAGE sql AS $$
	SELECT feature_id, feature_name, version, is_enabled, settings_assembly, settings_class, settings, date_created, last_updated, data FROM features;
$$;

CREATE OR REPLACE FUNCTION get_feature_by_feature_name_sp(p_feature_name varchar(255))
RETURNS TABLE ("FeatureID" integer, "FeatureName" varchar(255), "Version" varchar(255), "IsEnabled" boolean, "SettingsAssembly" varchar(255), "SettingsClass" varchar(255), "Settings" text, "DateCreated" timestamp, "LastUpdated" timestamp, "Data" text)
LANGUAGE sql AS $$
	SELECT feature_id, feature_name, version, is_enabled, settings_assembly, settings_class, settings, date_created, last_updated, data FROM features WHERE feature_name=p_feature_name;
$$;

CREATE OR REPLACE FUNCTION get_features_sp_count_sp(p_search varchar(255))
RETURNS integer LANGUAGE sql AS $$
	SELECT COUNT(*)::integer FROM features WHERE feature_id::varchar(50) LIKE '%'||COALESCE(p_search,'')||'%' OR feature_name LIKE '%'||COALESCE(p_search,'')||'%' OR version LIKE '%'||COALESCE(p_search,'')||'%' OR settings_assembly LIKE '%'||COALESCE(p_search,'')||'%' OR settings_class LIKE '%'||COALESCE(p_search,'')||'%';
$$;

CREATE OR REPLACE FUNCTION get_features_sp_paging_sp(p_search varchar(255), p_sort_column varchar(255), p_sort_ascending boolean, p_skip_rows integer, p_num_rows integer)
RETURNS TABLE ("FeatureID" integer, "FeatureName" varchar(255), "Version" varchar(255), "IsEnabled" boolean, "SettingsAssembly" varchar(255), "SettingsClass" varchar(255), "Settings" text, "DateCreated" timestamp, "LastUpdated" timestamp, "Data" text)
LANGUAGE sql AS $$
	SELECT feature_id, feature_name, version, is_enabled, settings_assembly, settings_class, settings, date_created, last_updated, data
	FROM features
	WHERE feature_id::varchar(50) LIKE '%'||COALESCE(p_search,'')||'%' OR feature_name LIKE '%'||COALESCE(p_search,'')||'%' OR version LIKE '%'||COALESCE(p_search,'')||'%' OR settings_assembly LIKE '%'||COALESCE(p_search,'')||'%' OR settings_class LIKE '%'||COALESCE(p_search,'')||'%'
	ORDER BY
		CASE WHEN p_sort_column='FeatureID' AND p_sort_ascending THEN feature_id END ASC,
		CASE WHEN p_sort_column='FeatureID' AND NOT p_sort_ascending THEN feature_id END DESC,
		CASE WHEN p_sort_column='FeatureName' AND p_sort_ascending THEN feature_name END ASC,
		CASE WHEN p_sort_column='FeatureName' AND NOT p_sort_ascending THEN feature_name END DESC,
		CASE WHEN p_sort_column='Version' AND p_sort_ascending THEN version END ASC,
		CASE WHEN p_sort_column='Version' AND NOT p_sort_ascending THEN version END DESC,
		CASE WHEN p_sort_column='IsEnabled' AND p_sort_ascending THEN is_enabled END ASC,
		CASE WHEN p_sort_column='IsEnabled' AND NOT p_sort_ascending THEN is_enabled END DESC,
		CASE WHEN p_sort_column='SettingsAssembly' AND p_sort_ascending THEN settings_assembly END ASC,
		CASE WHEN p_sort_column='SettingsAssembly' AND NOT p_sort_ascending THEN settings_assembly END DESC,
		CASE WHEN p_sort_column='SettingsClass' AND p_sort_ascending THEN settings_class END ASC,
		CASE WHEN p_sort_column='SettingsClass' AND NOT p_sort_ascending THEN settings_class END DESC,
		CASE WHEN p_sort_column='Settings' AND p_sort_ascending THEN settings END ASC,
		CASE WHEN p_sort_column='Settings' AND NOT p_sort_ascending THEN settings END DESC,
		CASE WHEN p_sort_column='DateCreated' AND p_sort_ascending THEN date_created END ASC,
		CASE WHEN p_sort_column='DateCreated' AND NOT p_sort_ascending THEN date_created END DESC,
		CASE WHEN p_sort_column='LastUpdated' AND p_sort_ascending THEN last_updated END ASC,
		CASE WHEN p_sort_column='LastUpdated' AND NOT p_sort_ascending THEN last_updated END DESC,
		CASE WHEN p_sort_column='Data' AND p_sort_ascending THEN data END ASC,
		CASE WHEN p_sort_column='Data' AND NOT p_sort_ascending THEN data END DESC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;

CREATE OR REPLACE FUNCTION mark_feature_as_enabled_sp(p_feature_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE features SET is_enabled=true, last_updated=now() WHERE feature_id=p_feature_id; $$;
CREATE OR REPLACE FUNCTION mark_feature_as_not_enabled_sp(p_feature_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE features SET is_enabled=false, last_updated=now() WHERE feature_id=p_feature_id; $$;
CREATE OR REPLACE FUNCTION update_feature_settings_sp(p_feature_id integer, p_settings text) RETURNS void LANGUAGE sql AS $$ UPDATE features SET settings=p_settings, last_updated=now() WHERE feature_id=p_feature_id; $$;
CREATE OR REPLACE FUNCTION update_feature_data_sp(p_feature_id integer, p_data text) RETURNS void LANGUAGE sql AS $$ UPDATE features SET data=p_data, last_updated=now() WHERE feature_id=p_feature_id; $$;


SELECT record_schema_migration('004_features_repository_routines');

