CREATE TABLE IF NOT EXISTS sessions (
	session_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_key text NOT NULL UNIQUE,
	agent_name text NOT NULL,
	project_name text NULL,
	project_file_path text NULL,
	provider text NOT NULL,
	model_name text NOT NULL,
	reasoning_level text NULL,
	prompt_context text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	data text NULL,
	session_name text NULL,
	parent_session_id integer NULL REFERENCES sessions(session_id),
	is_archived boolean NOT NULL DEFAULT false,
	compaction_provider text NULL
);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS compaction_provider text NULL;
CREATE INDEX IF NOT EXISTS ix_sessions_parent_session_id ON sessions(parent_session_id);

ALTER TABLE sessions ADD COLUMN IF NOT EXISTS state text NOT NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS session_kind text NOT NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS transport text NOT NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS active_turn_key text;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS current_turn_started_utc text;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_run_pulse_utc text;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_non_running_utc text;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS evaluate_admission_token text;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS needs_attention boolean NOT NULL DEFAULT false;
