CREATE TABLE IF NOT EXISTS sessions (
	session_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_key text NOT NULL UNIQUE,
	agent_name text NOT NULL,
	project_name text NULL,
	project_file_path text NULL,
	provider text NOT NULL,
	model_name text NOT NULL,
	reasoning_level text NULL,
	prompt_context text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	data text NULL,
	session_name text NULL,
	parent_session_id integer NULL REFERENCES sessions(session_id),
	is_archived boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_sessions_parent_session_id ON sessions(parent_session_id);

CREATE OR REPLACE FUNCTION insert_session_sp(p_session_key text,p_agent_name text,p_project_name text,p_project_file_path text,p_provider text,p_model_name text,p_reasoning_level text,p_prompt_context text,p_data text,p_session_name text,p_parent_session_id integer,p_is_archived boolean)
RETURNS TABLE ("SessionID" integer) LANGUAGE sql AS $$ INSERT INTO sessions(session_key,agent_name,project_name,project_file_path,provider,model_name,reasoning_level,prompt_context,date_created,last_updated,data,session_name,parent_session_id,is_archived) VALUES(p_session_key,p_agent_name,p_project_name,p_project_file_path,p_provider,p_model_name,p_reasoning_level,p_prompt_context,now(),now(),p_data,p_session_name,p_parent_session_id,p_is_archived) RETURNING session_id; $$;
CREATE OR REPLACE FUNCTION update_session_sp(p_session_id integer,p_session_key text,p_agent_name text,p_project_name text,p_project_file_path text,p_provider text,p_model_name text,p_reasoning_level text,p_prompt_context text,p_data text,p_session_name text,p_parent_session_id integer,p_is_archived boolean) RETURNS void LANGUAGE sql AS $$ UPDATE sessions SET session_key=p_session_key,agent_name=p_agent_name,project_name=p_project_name,project_file_path=p_project_file_path,provider=p_provider,model_name=p_model_name,reasoning_level=p_reasoning_level,prompt_context=p_prompt_context,last_updated=now(),data=p_data,session_name=p_session_name,parent_session_id=p_parent_session_id,is_archived=p_is_archived WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION remove_session_sp(p_session_id integer) RETURNS void LANGUAGE sql AS $$ DELETE FROM sessions WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION copy_session_sp(p_session_id integer) RETURNS TABLE ("SessionID" integer) LANGUAGE sql AS $$ INSERT INTO sessions(session_key,agent_name,project_name,project_file_path,provider,model_name,reasoning_level,prompt_context,date_created,last_updated,data,session_name,parent_session_id,is_archived) SELECT session_key || ' - Copy',agent_name,project_name,project_file_path,provider,model_name,reasoning_level,prompt_context,now(),now(),data,session_name,parent_session_id,is_archived FROM sessions WHERE session_id=p_session_id RETURNING session_id; $$;

CREATE OR REPLACE FUNCTION get_session_rows() RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$ SELECT session_id,session_key,agent_name,project_name,project_file_path,provider,model_name,reasoning_level,prompt_context,date_created,last_updated,data,session_name,parent_session_id,is_archived FROM sessions; $$;
CREATE OR REPLACE FUNCTION get_session_sp(p_session_id integer) RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$ SELECT * FROM get_session_rows() WHERE "SessionID"=p_session_id; $$;
CREATE OR REPLACE FUNCTION get_session_by_session_key_sp(p_session_key text) RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$ SELECT * FROM get_session_rows() WHERE "SessionKey"=p_session_key; $$;
CREATE OR REPLACE FUNCTION get_sessions_sp() RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$ SELECT * FROM get_session_rows(); $$;
CREATE OR REPLACE FUNCTION get_sessions_by_parent_session_id_sp(p_parent_session_id integer) RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$ SELECT * FROM get_session_rows() WHERE ((p_parent_session_id IS NULL AND "ParentSessionID" IS NULL) OR "ParentSessionID"=p_parent_session_id); $$;
CREATE OR REPLACE FUNCTION get_sessions_sp_count_sp(p_search text) RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$ SELECT COUNT(*)::integer FROM sessions WHERE session_id::text LIKE '%'||COALESCE(p_search,'')||'%' OR session_key LIKE '%'||COALESCE(p_search,'')||'%' OR agent_name LIKE '%'||COALESCE(p_search,'')||'%' OR project_name LIKE '%'||COALESCE(p_search,'')||'%' OR provider LIKE '%'||COALESCE(p_search,'')||'%' OR model_name LIKE '%'||COALESCE(p_search,'')||'%' OR session_name LIKE '%'||COALESCE(p_search,'')||'%'; $$;
CREATE OR REPLACE FUNCTION get_sessions_sp_paging_sp(p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer) RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$ SELECT * FROM get_session_rows() WHERE "SessionKey" LIKE '%'||COALESCE(p_search,'')||'%' OR "AgentName" LIKE '%'||COALESCE(p_search,'')||'%' OR "SessionName" LIKE '%'||COALESCE(p_search,'')||'%' ORDER BY CASE WHEN p_sort_column='SessionID' AND p_sort_ascending THEN "SessionID" END ASC, CASE WHEN p_sort_column='SessionID' AND NOT p_sort_ascending THEN "SessionID" END DESC, CASE WHEN p_sort_column='SessionKey' AND p_sort_ascending THEN "SessionKey" END ASC, CASE WHEN p_sort_column='SessionKey' AND NOT p_sort_ascending THEN "SessionKey" END DESC OFFSET p_skip_rows LIMIT p_num_rows; $$;
CREATE OR REPLACE FUNCTION mark_session_as_archived_sp(p_session_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE sessions SET is_archived=true,last_updated=now() WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION mark_session_as_not_archived_sp(p_session_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE sessions SET is_archived=false,last_updated=now() WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION update_session_data_sp(p_session_id integer,p_data text) RETURNS void LANGUAGE sql AS $$ UPDATE sessions SET data=p_data,last_updated=now() WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION update_session_name_sp(p_session_id integer,p_session_name text) RETURNS void LANGUAGE sql AS $$ UPDATE sessions SET session_name=p_session_name,last_updated=now() WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION update_session_parent_session_id_sp(p_session_id integer,p_parent_session_id integer) RETURNS void LANGUAGE sql AS $$ UPDATE sessions SET parent_session_id=p_parent_session_id,last_updated=now() WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION update_session_provider_selection_sp(p_session_id integer,p_provider text,p_model_name text,p_reasoning_level text,p_data text) RETURNS void LANGUAGE sql AS $$ UPDATE sessions SET provider=p_provider,model_name=p_model_name,reasoning_level=p_reasoning_level,data=p_data,last_updated=now() WHERE session_id=p_session_id; $$;
CREATE OR REPLACE FUNCTION sessions_reset_running_runtime_status_on_web_startup_sp() RETURNS void LANGUAGE sql AS $$ SELECT NULL::void; $$;




CREATE OR REPLACE FUNCTION session_matches_search(p_session sessions,p_search text)
RETURNS boolean LANGUAGE sql AS $$
	SELECT COALESCE(p_search,'') = ''
		OR p_session.session_id::text ILIKE '%' || COALESCE(p_search,'') || '%'
		OR p_session.session_key ILIKE '%' || COALESCE(p_search,'') || '%'
		OR p_session.agent_name ILIKE '%' || COALESCE(p_search,'') || '%'
		OR COALESCE(p_session.project_name,'') ILIKE '%' || COALESCE(p_search,'') || '%'
		OR COALESCE(p_session.project_file_path,'') ILIKE '%' || COALESCE(p_search,'') || '%'
		OR p_session.provider ILIKE '%' || COALESCE(p_search,'') || '%'
		OR p_session.model_name ILIKE '%' || COALESCE(p_search,'') || '%'
		OR COALESCE(p_session.reasoning_level,'') ILIKE '%' || COALESCE(p_search,'') || '%'
		OR COALESCE(p_session.session_name,'') ILIKE '%' || COALESCE(p_search,'') || '%';
$$;

CREATE OR REPLACE FUNCTION sessions_get_effective_last_updated(p_session_id integer,p_archived boolean)
RETURNS timestamp LANGUAGE sql AS $$
	SELECT GREATEST(p.last_updated, COALESCE(MAX(c.last_updated), p.last_updated))
	FROM sessions p
	LEFT JOIN sessions c ON c.parent_session_id = p.session_id AND c.is_archived = p_archived
	WHERE p.session_id = p_session_id
	GROUP BY p.last_updated;
$$;

CREATE OR REPLACE FUNCTION sessions_get_all_sp()
RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$
	SELECT * FROM get_session_rows() WHERE "IsArchived" = false;
$$;

CREATE OR REPLACE FUNCTION sessions_get_all_sp_count_sp(p_search text)
RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$
	SELECT COUNT(*)::integer FROM sessions s WHERE s.is_archived = false AND session_matches_search(s, p_search);
$$;

CREATE OR REPLACE FUNCTION sessions_get_all_sp_paging_sp(p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer)
RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$
	SELECT s.session_id,s.session_key,s.agent_name,s.project_name,s.project_file_path,s.provider,s.model_name,s.reasoning_level,s.prompt_context,s.date_created,sessions_get_effective_last_updated(s.session_id,false),s.data,s.session_name,s.parent_session_id,s.is_archived
	FROM sessions s
	WHERE s.is_archived = false AND session_matches_search(s, p_search)
	ORDER BY
		CASE WHEN p_sort_column='LastUpdated' AND p_sort_ascending THEN sessions_get_effective_last_updated(s.session_id,false) END ASC,
		CASE WHEN p_sort_column='LastUpdated' AND NOT p_sort_ascending THEN sessions_get_effective_last_updated(s.session_id,false) END DESC,
		CASE WHEN p_sort_column='SessionID' AND p_sort_ascending THEN s.session_id END ASC,
		CASE WHEN p_sort_column='SessionID' AND NOT p_sort_ascending THEN s.session_id END DESC,
		CASE WHEN p_sort_column='SessionKey' AND p_sort_ascending THEN s.session_key END ASC,
		CASE WHEN p_sort_column='SessionKey' AND NOT p_sort_ascending THEN s.session_key END DESC,
		sessions_get_effective_last_updated(s.session_id,false) DESC,
		s.session_id DESC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;

CREATE OR REPLACE FUNCTION sessions_get_archived_sp_sp()
RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$
	SELECT * FROM get_session_rows() WHERE "IsArchived" = true;
$$;

CREATE OR REPLACE FUNCTION sessions_get_archived_sp_sp_count_sp(p_search text)
RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$
	SELECT COUNT(*)::integer FROM sessions s WHERE s.is_archived = true AND session_matches_search(s, p_search);
$$;

CREATE OR REPLACE FUNCTION sessions_get_archived_sp_sp_paging_sp(p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer)
RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$
	SELECT s.session_id,s.session_key,s.agent_name,s.project_name,s.project_file_path,s.provider,s.model_name,s.reasoning_level,s.prompt_context,s.date_created,sessions_get_effective_last_updated(s.session_id,true),s.data,s.session_name,s.parent_session_id,s.is_archived
	FROM sessions s
	WHERE s.is_archived = true AND session_matches_search(s, p_search)
	ORDER BY
		CASE WHEN p_sort_column='LastUpdated' AND p_sort_ascending THEN sessions_get_effective_last_updated(s.session_id,true) END ASC,
		CASE WHEN p_sort_column='LastUpdated' AND NOT p_sort_ascending THEN sessions_get_effective_last_updated(s.session_id,true) END DESC,
		CASE WHEN p_sort_column='SessionID' AND p_sort_ascending THEN s.session_id END ASC,
		CASE WHEN p_sort_column='SessionID' AND NOT p_sort_ascending THEN s.session_id END DESC,
		CASE WHEN p_sort_column='SessionKey' AND p_sort_ascending THEN s.session_key END ASC,
		CASE WHEN p_sort_column='SessionKey' AND NOT p_sort_ascending THEN s.session_key END DESC,
		sessions_get_effective_last_updated(s.session_id,true) DESC,
		s.session_id DESC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;

CREATE OR REPLACE FUNCTION get_sessions_by_parent_session_idsp_count_sp(p_parent_session_id integer,p_search text)
RETURNS TABLE ("Total" integer) LANGUAGE sql AS $$
	SELECT COUNT(*)::integer FROM sessions s WHERE s.parent_session_id = p_parent_session_id AND session_matches_search(s, p_search);
$$;

CREATE OR REPLACE FUNCTION get_sessions_by_parent_session_idsp_paging_sp(p_parent_session_id integer,p_search text,p_sort_column text,p_sort_ascending boolean,p_skip_rows integer,p_num_rows integer)
RETURNS TABLE ("SessionID" integer,"SessionKey" text,"AgentName" text,"ProjectName" text,"ProjectFilePath" text,"Provider" text,"ModelName" text,"ReasoningLevel" text,"PromptContext" text,"DateCreated" timestamp,"LastUpdated" timestamp,"Data" text,"SessionName" text,"ParentSessionID" integer,"IsArchived" boolean) LANGUAGE sql AS $$
	SELECT * FROM get_session_rows() r
	WHERE r."ParentSessionID" = p_parent_session_id AND EXISTS (SELECT 1 FROM sessions s WHERE s.session_id = r."SessionID" AND session_matches_search(s, p_search))
	ORDER BY
		CASE WHEN p_sort_column='SessionID' AND p_sort_ascending THEN r."SessionID" END ASC,
		CASE WHEN p_sort_column='SessionID' AND NOT p_sort_ascending THEN r."SessionID" END DESC,
		CASE WHEN p_sort_column='SessionKey' AND p_sort_ascending THEN r."SessionKey" END ASC,
		CASE WHEN p_sort_column='SessionKey' AND NOT p_sort_ascending THEN r."SessionKey" END DESC,
		r."SessionID" DESC
	OFFSET p_skip_rows LIMIT p_num_rows;
$$;

CREATE OR REPLACE FUNCTION cleanup_test_sessions_archive_sp(p_preview_only boolean DEFAULT true)
RETURNS TABLE ("MatchReason" text,"SessionCount" integer) LANGUAGE plpgsql AS $$
BEGIN
	CREATE TEMP TABLE cleanup_test_session_candidates ON COMMIT DROP AS
	SELECT s.session_id,
		CASE
			WHEN s.session_key ~ '^[0-9a-f]{32}$' THEN 'guid_like'
			WHEN s.session_key ~ '^[0-9a-f]{32}-level-two$' THEN 'guid_level_two'
			WHEN COALESCE(s.session_name,'') ~ '^CorePath Renamed [0-9a-f]{6,12}$' THEN 'corepath_renamed_random'
			ELSE NULL
		END AS match_reason
	FROM sessions s
	WHERE s.is_archived = false;

	DELETE FROM cleanup_test_session_candidates WHERE match_reason IS NULL;

	IF p_preview_only = false THEN
		UPDATE sessions s SET is_archived = true,last_updated = now()
		FROM cleanup_test_session_candidates c
		WHERE c.session_id = s.session_id;
	END IF;

	RETURN QUERY SELECT c.match_reason, COUNT(*)::integer FROM cleanup_test_session_candidates c GROUP BY c.match_reason ORDER BY c.match_reason;
END;
$$;
SELECT record_schema_migration('005_sessions_repository_routines');


DROP FUNCTION IF EXISTS update_session_date_created_sp(integer,timestamp);
DROP FUNCTION IF EXISTS "UpdateSessionDateCreatedSp"(integer,timestamp);

CREATE OR REPLACE FUNCTION update_session_date_created_sp(p_session_id integer,p_date_created timestamp)
RETURNS void LANGUAGE sql AS $$
	UPDATE sessions SET date_created = p_date_created WHERE session_id = p_session_id;
$$;

CREATE OR REPLACE FUNCTION "UpdateSessionDateCreatedSp"(p_session_id integer,p_date_created timestamp)
RETURNS void LANGUAGE sql AS $$
SELECT update_session_date_created_sp(p_session_id,p_date_created);
$$;
