CREATE TABLE IF NOT EXISTS messages (
	message_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id integer NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
	sequence_number integer NOT NULL,
	role text NOT NULL,
	content text NOT NULL,
	tool_name text NULL,
	tool_arguments text NULL,
	call_id text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now(),
	data text NULL,
	is_compacted boolean NOT NULL DEFAULT false,
	compaction_epoch integer NULL,
	message_key text NOT NULL,
	turn_id text NOT NULL,
	compaction_epoch_key text NULL,
	turn_row_id bigint NULL
);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS turn_row_id bigint NULL;
DROP INDEX IF EXISTS ix_messages_message_key;
CREATE UNIQUE INDEX IF NOT EXISTS ux_messages_message_key ON messages(message_key);
CREATE INDEX IF NOT EXISTS ix_messages_session_id_message_id ON messages(session_id, message_id);
CREATE INDEX IF NOT EXISTS ix_messages_session_id_message_key ON messages(session_id, message_key);
CREATE INDEX IF NOT EXISTS ix_messages_session_id_sequence_number ON messages(session_id, sequence_number, message_id);
CREATE INDEX IF NOT EXISTS ix_messages_turn_id ON messages(turn_id);
CREATE INDEX IF NOT EXISTS ix_messages_compaction_epoch_key ON messages(compaction_epoch_key);
CREATE INDEX IF NOT EXISTS ix_messages_session_id_compaction_epoch_key_message_id ON messages(session_id, compaction_epoch_key, message_id);


ALTER TABLE messages ADD COLUMN IF NOT EXISTS message_kind text;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS terminal_outcome_state text;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS saved_work_resume boolean;
CREATE OR REPLACE VIEW message_rows AS
	SELECT message_id AS "MessageID",session_id AS "SessionID",sequence_number AS "SequenceNumber",role AS "Role",content AS "Content",tool_name AS "ToolName",tool_arguments AS "ToolArguments",call_id AS "CallID",date_created AS "DateCreated",last_updated AS "LastUpdated",data AS "Data",is_compacted AS "IsCompacted",compaction_epoch AS "CompactionEpoch",message_key AS "MessageKey",turn_id AS "TurnID",compaction_epoch_key AS "CompactionEpochKey",turn_row_id AS "TurnRowID",message_kind AS "MessageKind",terminal_outcome_state AS "TerminalOutcomeState",saved_work_resume AS "SavedWorkResume"
	FROM messages;
