-- PostgreSQL FragmentMessageMap schema and repository routines.
-- Result aliases preserve the SQL Server repository row contract used by generated C# callers.

CREATE TABLE IF NOT EXISTS fragment_message_map (
	fragment_message_map_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fragment_id integer NOT NULL REFERENCES fragments(fragment_id) ON DELETE CASCADE,
	session_id integer NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
	message_id integer NULL REFERENCES messages(message_id) ON DELETE CASCADE,
	mapping_type varchar(100) NOT NULL,
	sort_order integer NOT NULL DEFAULT 0,
	data text NULL,
	date_created timestamp NOT NULL DEFAULT now(),
	last_updated timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_fragment_message_map_fragment_id ON fragment_message_map(fragment_id);
CREATE INDEX IF NOT EXISTS ix_fragment_message_map_message_id ON fragment_message_map(message_id);
CREATE INDEX IF NOT EXISTS ix_fragment_message_map_session_id ON fragment_message_map(session_id, mapping_type, sort_order);

CREATE OR REPLACE FUNCTION insert_fragment_message_map_sp(
	p_fragment_id integer,
	p_session_id integer,
	p_message_id integer DEFAULT NULL,
	p_mapping_type varchar(100) DEFAULT NULL,
	p_sort_order integer DEFAULT 0,
	p_data text DEFAULT NULL
)
RETURNS TABLE (FragmentMessageMapID integer)
LANGUAGE sql
AS $$
	INSERT INTO fragment_message_map (fragment_id, session_id, message_id, mapping_type, sort_order, data, date_created, last_updated)
	VALUES (p_fragment_id, p_session_id, p_message_id, p_mapping_type, COALESCE(p_sort_order, 0), p_data, now(), now())
	RETURNING fragment_message_map_id;
$$;

CREATE OR REPLACE FUNCTION remove_fragment_message_map_by_fragment_id_sp(p_fragment_id integer)
RETURNS void
LANGUAGE sql
AS $$
	DELETE FROM fragment_message_map WHERE fragment_id = p_fragment_id;
$$;

CREATE OR REPLACE FUNCTION get_fragment_message_map_by_fragment_id_sp(p_fragment_id integer)
RETURNS TABLE (FragmentMessageMapID integer, FragmentID integer, SessionID integer, MessageID integer, MappingType varchar(100), SortOrder integer, Data text)
LANGUAGE sql
AS $$
	SELECT fragment_message_map_id, fragment_id, session_id, message_id, mapping_type, sort_order, data
	FROM fragment_message_map
	WHERE fragment_id = p_fragment_id
	ORDER BY sort_order ASC, fragment_message_map_id ASC;
$$;

CREATE OR REPLACE FUNCTION get_fragment_message_map_by_session_id_sp(p_session_id integer)
RETURNS TABLE (FragmentMessageMapID integer, FragmentID integer, SessionID integer, MessageID integer, MappingType varchar(100), SortOrder integer, Data text)
LANGUAGE sql
AS $$
	SELECT fragment_message_map_id, fragment_id, session_id, message_id, mapping_type, sort_order, data
	FROM fragment_message_map
	WHERE session_id = p_session_id
	ORDER BY mapping_type ASC, sort_order ASC, fragment_message_map_id ASC;
$$;


SELECT record_schema_migration('008_fragment_message_map_repository_routines');
