-- Session-owned atomic compaction projection; no execution Turn is created or mutated.
DROP TYPE IF EXISTS authoritative_session_compaction_receipt_rows CASCADE;
CREATE TYPE authoritative_session_compaction_receipt_rows AS ("OperationKey" uuid,"HistoryGeneration" bigint,"MovedRows" integer,"InsertedRows" integer,"IsReplay" boolean);
ALTER TABLE turn_mutation_receipts DROP CONSTRAINT IF EXISTS ck_turn_receipt_kind;
ALTER TABLE turn_mutation_receipts ADD CONSTRAINT ck_turn_receipt_kind CHECK(mutation_kind IN('Begin','Append','UpdateExistingMessage','Pause','Resume','Handoff','Finish','Interrupt','Compaction','Clear','HistoricalImport','MoveMessageEpoch','MoveToolPairEpoch','PersistSessionCompaction'));
CREATE OR REPLACE FUNCTION "Turns_PersistSessionCompaction"(p_session_id integer,p_operation_key uuid,p_history_generation bigint,p_owner_turn_key text,p_writer_token uuid,p_target_epoch integer,p_target_epoch_key text,p_session_data text,p_request_contract text,p_request_payload bytea,p_request_fingerprint bytea)
RETURNS SETOF authoritative_session_compaction_receipt_rows LANGUAGE plpgsql AS $$
DECLARE state session_turn_state%ROWTYPE;prior turn_mutation_receipts%ROWTYPE;moved integer;inserted integer;next_sequence integer;now_utc timestamp:=timezone('utc',clock_timestamp());
BEGIN
 IF p_session_id<=0 OR p_operation_key IS NULL OR p_history_generation<1 OR p_target_epoch<0 OR p_target_epoch_key IS NULL OR length(p_target_epoch_key)=0 OR p_session_data IS NULL OR p_request_contract IS NULL OR p_request_payload IS NULL OR sha256(p_request_payload)<>p_request_fingerprint THEN RAISE EXCEPTION 'Invalid session compaction contract.';END IF;
 IF (p_owner_turn_key IS NULL)<>(p_writer_token IS NULL) THEN RAISE EXCEPTION 'Compaction owner coordinates must be supplied together.';END IF;
 PERFORM 1 FROM sessions WHERE session_id=p_session_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Session does not exist.';END IF;
 SELECT * INTO state FROM session_turn_state WHERE session_id=p_session_id FOR UPDATE;IF NOT FOUND OR state.authority_status<>'Authoritative' OR state.authority_contract_version<>1 OR state.writer_fence OR state.history_generation<>p_history_generation THEN RAISE EXCEPTION 'Compaction generation conflict.';END IF;
 IF state.active_turn_key IS NULL THEN IF p_owner_turn_key IS NOT NULL THEN RAISE EXCEPTION 'Idle compaction cannot claim owner.';END IF; ELSE IF p_owner_turn_key IS NULL OR state.active_turn_key COLLATE "C"<>p_owner_turn_key COLLATE "C" OR NOT EXISTS(SELECT 1 FROM turns WHERE session_id=p_session_id AND turn_key COLLATE "C"=p_owner_turn_key COLLATE "C" AND writer_token=p_writer_token AND state IN('InProgress','Paused') AND NOT is_deleted) THEN RAISE EXCEPTION 'Compaction writer conflict.';END IF;END IF;
 SELECT * INTO prior FROM turn_mutation_receipts WHERE session_id=p_session_id AND operation_key=p_operation_key;IF FOUND THEN IF prior.mutation_kind<>'PersistSessionCompaction' OR prior.request_payload<>p_request_payload OR prior.result_history_generation<>p_history_generation THEN RAISE EXCEPTION 'Compaction replay conflict.';END IF;SELECT count(*) INTO moved FROM jsonb_array_elements(p_request_contract::jsonb->'RetainedMessages');SELECT count(*) INTO inserted FROM jsonb_array_elements(p_request_contract::jsonb->'InsertedMessages');RETURN QUERY SELECT p_operation_key,p_history_generation,moved,inserted,true;RETURN;END IF;
 IF EXISTS(SELECT 1 FROM jsonb_to_recordset(p_request_contract::jsonb->'RetainedMessages') r("MessageKey" text,"SourceEpoch" integer,"SourceEpochKey" text) LEFT JOIN messages m ON m.session_id=p_session_id AND m.message_key COLLATE "C"=r."MessageKey" COLLATE "C" WHERE m.message_id IS NULL OR m.compaction_epoch IS DISTINCT FROM r."SourceEpoch" OR m.compaction_epoch_key IS DISTINCT FROM r."SourceEpochKey") THEN RAISE EXCEPTION 'Retained message source conflict.';END IF;
 UPDATE messages m SET compaction_epoch=p_target_epoch,compaction_epoch_key=p_target_epoch_key FROM jsonb_to_recordset(p_request_contract::jsonb->'RetainedMessages') r("MessageKey" text) WHERE m.session_id=p_session_id AND m.message_key COLLATE "C"=r."MessageKey" COLLATE "C";GET DIAGNOSTICS moved=ROW_COUNT;
	PERFORM 1 FROM messages WHERE session_id=p_session_id FOR UPDATE;
	SELECT coalesce(max(sequence_number),0) INTO next_sequence FROM messages WHERE session_id=p_session_id;
 IF EXISTS(SELECT 1 FROM jsonb_to_recordset(p_request_contract::jsonb->'InsertedMessages') i("MessageKey" text,"TurnKey" text) LEFT JOIN turns t ON t.session_id=p_session_id AND t.turn_key COLLATE "C"=i."TurnKey" COLLATE "C" AND NOT t.is_deleted WHERE t.session_id IS NULL) OR EXISTS(SELECT 1 FROM jsonb_to_recordset(p_request_contract::jsonb->'InsertedMessages') i("MessageKey" text) JOIN messages m ON m.message_key COLLATE "C"=i."MessageKey" COLLATE "C") THEN RAISE EXCEPTION 'Inserted compaction message identity conflict.';END IF;
 INSERT INTO messages(session_id,sequence_number,role,content,tool_name,tool_arguments,call_id,date_created,last_updated,data,is_compacted,compaction_epoch,message_key,turn_id,compaction_epoch_key) SELECT p_session_id,next_sequence+row_number() OVER(),i."Role",i."Content",i."ToolName",i."ToolArguments",i."CallID",i."DateCreatedUtc",now_utc,i."Data",i."IsCompacted",p_target_epoch,i."MessageKey",i."TurnKey",p_target_epoch_key FROM jsonb_to_recordset(p_request_contract::jsonb->'InsertedMessages') i("MessageKey" text,"TurnKey" text,"Role" text,"Content" text,"ToolName" text,"ToolArguments" text,"CallID" text,"DateCreatedUtc" timestamp,"Data" text,"IsCompacted" boolean);GET DIAGNOSTICS inserted=ROW_COUNT;
 UPDATE sessions SET data=p_session_data,last_updated=now_utc WHERE session_id=p_session_id;UPDATE session_turn_state SET last_updated_at_utc=now_utc WHERE session_id=p_session_id;
 INSERT INTO turn_mutation_receipts(session_id,operation_key,turn_key,turn_identity,mutation_kind,request_fingerprint,request_payload,mutation_version,change_revision,occurred_at_utc,persisted_at_utc,is_tombstone,result_history_generation) VALUES(p_session_id,p_operation_key,coalesce(p_owner_turn_key,'compaction-session'),authoritative_turn_identity(coalesce(p_owner_turn_key,'compaction-session')),'PersistSessionCompaction',p_request_fingerprint,p_request_payload,1,state.committed_revision,now_utc,now_utc,false,p_history_generation);
 RETURN QUERY SELECT p_operation_key,p_history_generation,moved,inserted,false;
END $$;
SELECT record_schema_migration('028_authoritative_turns_session_compaction');
